function renderSharedComponentStyles() {
  return [
    '    <style>',
    '      .noctalia-premium-nav { background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none; }',
    '      .noctalia-premium-nav.py-2 { background: rgba(10, 5, 20, 0.78); backdrop-filter: blur(18px); -webkit-backdrop-filter: blur(18px); box-shadow: 0 12px 34px rgba(0, 0, 0, 0.24); }',
    '      .noctalia-premium-nav-inner { position: relative; z-index: 70; width: 100%; max-width: 1720px; margin: 0 auto; display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: clamp(1rem, 3vw, 3.5rem); }',
    '      .noctalia-premium-links { justify-content: center; flex-wrap: nowrap; gap: clamp(1.4rem, 3.4vw, 4rem); min-width: 0; }',
    '      .noctalia-premium-nav-actions { justify-content: flex-end; }',
    '      .noctalia-premium-action { display: inline-flex; }',
    '      .noctalia-premium-download { display: inline-flex; align-items: center; justify-content: center; color: rgba(237, 225, 255, 0.86); background: rgba(255, 255, 255, 0.06); border: 1px solid rgba(255, 255, 255, 0.12); }',
    '      .noctalia-premium-download:hover { color: #fff; background: rgba(255, 255, 255, 0.10); border-color: rgba(253, 164, 129, 0.35); }',
    '      body.mobile-menu-lock { overflow: hidden; touch-action: none; }',
    '      main .overflow-x-auto { max-width: 100%; overflow-x: auto !important; overscroll-behavior-inline: contain; }',
    '      .mobile-menu-backdrop { position: fixed; inset: 0; z-index: 48; background: rgba(5, 2, 12, 0.72); opacity: 0; transition: opacity 180ms ease; }',
    '      .mobile-menu-backdrop.is-visible { opacity: 1; }',
    '      #mobileMenuPanel { position: fixed; left: 0; right: 0; top: 4.25rem; bottom: 0; z-index: 60; }',
    '      .mobile-menu-surface { min-height: calc(100dvh - 5.25rem); max-height: calc(100dvh - 5.25rem); overflow-y: auto; background: #120720 !important; border: 1px solid rgba(255, 255, 255, 0.12); box-shadow: 0 18px 48px rgba(0, 0, 0, 0.52); backdrop-filter: none !important; -webkit-backdrop-filter: none !important; }',
    '      .site-footer { position: relative; z-index: 2; background: #05020a !important; }',
    '      .site-footer > .grid { position: relative; z-index: 1; }',
    '      .page-hero-illustrated { position: relative; left: 50%; isolation: isolate; display: grid; width: 100vw; min-height: max(40rem, 78svh); align-items: end; overflow: hidden; transform: translateX(-50%); }',
    '      .page-hero-illustrated::after { content: ""; position: absolute; inset: 0; z-index: 1; pointer-events: none; background: linear-gradient(180deg, rgba(7, 3, 15, 0.2) 0%, rgba(7, 3, 15, 0.34) 42%, rgba(7, 3, 15, 0.94) 100%), linear-gradient(90deg, rgba(7, 3, 15, 0.46), rgba(7, 3, 15, 0.08) 52%, rgba(7, 3, 15, 0.42)); }',
    '      .page-hero-illustration { position: absolute; inset: 0; z-index: 0; width: 100%; height: 100%; margin: 0; overflow: hidden; }',
    '      .page-hero-illustration picture, .page-hero-illustration img { display: block; width: 100%; height: 100%; }',
    '      .page-hero-illustration img { object-fit: cover; object-position: center; }',
    '      .page-hero-illustration figcaption { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); clip-path: inset(50%); white-space: nowrap; border: 0; }',
    '      .page-hero-illustrated > .page-hero-copy { position: relative; z-index: 2; width: 100%; text-shadow: 0 2px 24px rgba(0, 0, 0, 0.72); }',
    '      .pseo-illustrated-hero { position: relative; left: 50%; isolation: isolate; display: grid; width: 100vw; min-height: max(40rem, 78svh); margin: 0 0 3rem; padding: clamp(6rem, 11vw, 9rem) max(1.5rem, calc((100vw - 64rem) / 2)) clamp(2.5rem, 7vw, 5rem); align-items: end; overflow: hidden; transform: translateX(-50%); }',
    '      .pseo-illustrated-hero::after { content: ""; position: absolute; inset: 0; z-index: 1; pointer-events: none; background: linear-gradient(180deg, rgba(7, 3, 15, 0.18), rgba(7, 3, 15, 0.32) 44%, rgba(7, 3, 15, 0.96)), linear-gradient(90deg, rgba(7, 3, 15, 0.48), rgba(7, 3, 15, 0.08) 54%, rgba(7, 3, 15, 0.42)); }',
    '      .pseo-hero-illustration { position: absolute; inset: 0; z-index: 0; width: 100%; height: 100%; margin: 0; overflow: hidden; }',
    '      .pseo-hero-illustration picture, .pseo-hero-illustration img { display: block; width: 100%; height: 100%; }',
    '      .pseo-hero-illustration img { object-fit: cover; object-position: center; }',
    '      .pseo-hero-illustration figcaption { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); clip-path: inset(50%); white-space: nowrap; border: 0; }',
    '      .pseo-hero-copy { position: relative; z-index: 2; width: 100%; max-width: 64rem; margin: 0 auto; text-align: center; text-shadow: 0 2px 24px rgba(0, 0, 0, 0.74); }',
    '      @media (max-width: 1100px) { .noctalia-premium-download, .noctalia-premium-about { display: none; } .noctalia-premium-links { gap: clamp(1rem, 2.5vw, 2rem); } }',
    '      @media (max-width: 860px) { .noctalia-premium-nav-inner { display: flex; justify-content: space-between; } .noctalia-premium-nav-actions { margin-left: auto; } .noctalia-premium-links { display: none; } #navMobileGuideLink, #mobileMenuButton { display: inline-flex; } }',
    '      @media (max-width: 767px) { .page-hero-illustrated { min-height: clamp(34rem, 132vw, 46rem); padding: 7rem 1.25rem 2.5rem !important; } .page-hero-illustration img { object-position: 50% 50%; } .pseo-illustrated-hero { min-height: clamp(34rem, 132vw, 46rem); padding: 6.5rem 1.25rem 2.5rem; } .pseo-hero-illustration img { object-position: 50% 50%; } .site-footer { padding: 2rem 1rem 1.75rem !important; } .site-footer > .grid { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1.5rem 1rem; margin-bottom: 2rem; } .site-footer > .grid > :first-child { grid-column: 1 / -1; display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 0.45rem 1rem; align-items: center; padding-bottom: 1rem; border-bottom: 1px solid rgba(255, 255, 255, 0.08); } .site-footer > .grid > :first-child > a { grid-column: 1; grid-row: 1; margin-bottom: 0; } .site-footer > .grid > :first-child > p { grid-column: 1; grid-row: 2; margin-bottom: 0; max-width: 17rem; } .site-footer > .grid > :first-child > div.flex { grid-column: 2; grid-row: 1 / span 2; gap: 0.45rem; } .site-footer > .grid > :first-child > div.flex a { width: 2.35rem; height: 2.35rem; } .site-footer h5 { margin-bottom: 0.65rem; font-size: 0.76rem; letter-spacing: 0.08em; text-transform: uppercase; color: rgba(255, 247, 240, 0.92); } .site-footer ul { font-size: 0.82rem; line-height: 1.35; } .site-footer li + li { margin-top: 0.45rem; } .site-footer > .grid > :nth-child(2) ul, .site-footer > .grid > :nth-child(3) ul { max-height: 11.5rem; overflow-y: auto; padding-right: 0.35rem; } .site-footer > .grid > :nth-child(2) ul::-webkit-scrollbar, .site-footer > .grid > :nth-child(3) ul::-webkit-scrollbar { width: 0.25rem; } .site-footer > .grid > :nth-child(2) ul::-webkit-scrollbar-thumb, .site-footer > .grid > :nth-child(3) ul::-webkit-scrollbar-thumb { background: rgba(253, 164, 129, 0.45); border-radius: 999px; } .site-footer > .border-t:last-child { padding-top: 1rem; } }',
    '      @media (max-width: 520px) { .noctalia-premium-nav-inner { padding-left: 1rem; padding-right: 1rem; } .noctalia-premium-brand-text { font-size: 1.35rem; } #navMobileGuideLink { display: none; } }',
    '    </style>',
  ].join('\n');
}

module.exports = {
  renderSharedComponentStyles,
};
