// plugins/withSoftExceptionLogging.js
//
// React Native reports recoverable inconsistencies through
// `ReactSoftExceptionLogger`. Several of them — notably
// `SurfaceMountingManager.addViewAt: cannot insert view [..]: View already has
// a parent` — are logged immediately before the mount instruction that actually
// crashes the process. With no listener registered those lines only reach
// logcat, which is long gone by the time a user reports the crash.
//
// This plugin registers a listener that mirrors every soft exception to a
// greppable tag and persists it synchronously, then replays anything persisted
// on the next launch. That turns a one-off "it happened once" report into an
// artifact naming the offending view and its stale parent.
//
// `ReactSoftExceptionLogger` is `internal` in Kotlin but compiles to a plain
// `public static final addListener(..)` with no name mangling, so the listener
// has to be written in Java — Kotlin would reject it at compile time.
const { withDangerousMod, withMainApplication } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const INSTALL_COMMENT =
  '// Capture React Native soft exceptions before a later hard crash discards them.';
const INSTALL_CALL = 'NoctaliaSoftExceptionLogger.install(this)';
const JAVA_CLASS_NAME = 'NoctaliaSoftExceptionLogger';

function buildSoftExceptionLoggerSource(packageName) {
  if (!packageName) {
    throw new Error('Soft exception logging requires an Android package name.');
  }

  return `package ${packageName};

// Generated by plugins/withSoftExceptionLogging.js — do not edit by hand.

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

import com.facebook.react.bridge.ReactSoftExceptionLogger;

import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Mirrors React Native soft exceptions to logcat and to durable storage.
 *
 * <p>React Native only logs soft exceptions itself while no listener is
 * registered, so this listener must keep logging them or observability would go
 * down rather than up.
 */
public final class ${JAVA_CLASS_NAME} {

  public static final String TAG = "NoctaliaSoftException";

  private static final String PREFS_NAME = "noctalia_soft_exceptions";
  private static final String ENTRIES_KEY = "entries";
  private static final String RECORD_SEPARATOR = "\\u001e";
  private static final int MAX_ENTRIES = 20;
  private static final int MAX_STACK_FRAMES = 12;
  private static final int MAX_PERSISTED_PER_PROCESS = 20;

  private static final AtomicBoolean INSTALLED = new AtomicBoolean(false);
  private static final AtomicInteger PERSISTED_THIS_PROCESS = new AtomicInteger(0);

  private ${JAVA_CLASS_NAME}() {}

  /** Idempotent; safe to call from {@code Application.onCreate}. */
  public static void install(Context context) {
    if (!INSTALLED.compareAndSet(false, true)) {
      return;
    }

    final Context appContext = context.getApplicationContext();
    replayPersistedEntries(appContext);

    ReactSoftExceptionLogger.addListener(
        new ReactSoftExceptionLogger.ReactSoftExceptionListener() {
          @Override
          public void logSoftException(String category, Throwable cause) {
            Log.e(TAG, "category=" + category, cause);
            persistEntry(appContext, category, cause);
          }
        });
  }

  /**
   * Persisted with {@code commit()} rather than {@code apply()} on purpose: the
   * process may be a few milliseconds from dying, and an async write would be
   * lost exactly when it matters.
   *
   * <p>Soft exceptions can arrive one per mount instruction, so persistence is
   * capped per process. Everything still reaches logcat; only the durable write
   * stops, which keeps a storm from turning into synchronous disk I/O on the
   * mounting thread.
   */
  private static void persistEntry(Context context, String category, Throwable cause) {
    if (PERSISTED_THIS_PROCESS.incrementAndGet() > MAX_PERSISTED_PER_PROCESS) {
      return;
    }

    try {
      SharedPreferences prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE);
      String existing = prefs.getString(ENTRIES_KEY, "");
      String entry = System.currentTimeMillis() + " category=" + category + " " + summarize(cause);

      String combined = existing.isEmpty() ? entry : existing + RECORD_SEPARATOR + entry;
      String[] records = combined.split(RECORD_SEPARATOR, -1);
      if (records.length > MAX_ENTRIES) {
        StringBuilder trimmed = new StringBuilder();
        for (int i = records.length - MAX_ENTRIES; i < records.length; i++) {
          if (trimmed.length() > 0) {
            trimmed.append(RECORD_SEPARATOR);
          }
          trimmed.append(records[i]);
        }
        combined = trimmed.toString();
      }

      prefs.edit().putString(ENTRIES_KEY, combined).commit();
    } catch (Throwable ignored) {
      // Diagnostics must never be the reason the app fails.
    }
  }

  private static void replayPersistedEntries(Context context) {
    try {
      SharedPreferences prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE);
      String stored = prefs.getString(ENTRIES_KEY, "");
      if (stored.isEmpty()) {
        return;
      }
      prefs.edit().remove(ENTRIES_KEY).commit();

      String[] records = stored.split(RECORD_SEPARATOR, -1);
      for (String record : records) {
        if (!record.isEmpty()) {
          Log.e(TAG, "replay " + record);
        }
      }
    } catch (Throwable ignored) {
      // See persistEntry.
    }
  }

  private static String summarize(Throwable cause) {
    if (cause == null) {
      return "cause=none";
    }

    StringBuilder builder = new StringBuilder();
    builder.append(cause.getClass().getName()).append(": ").append(cause.getMessage());

    StackTraceElement[] frames = cause.getStackTrace();
    int limit = Math.min(frames.length, MAX_STACK_FRAMES);
    for (int i = 0; i < limit; i++) {
      builder.append(" | ").append(frames[i].toString());
    }
    if (frames.length > limit) {
      builder.append(" | ... ").append(frames.length - limit).append(" more");
    }

    Throwable root = cause.getCause();
    if (root != null) {
      builder.append(" | caused by ").append(root.getClass().getName())
          .append(": ").append(root.getMessage());
      StackTraceElement[] rootFrames = root.getStackTrace();
      if (rootFrames.length > 0) {
        builder.append(" | ").append(rootFrames[0].toString());
      }
    }

    // Newlines would break the one-record-per-line logcat contract.
    return builder.toString().replace('\\n', ' ').replace('\\r', ' ');
  }
}
`;
}

function applyMainApplicationInstall(contents) {
  let next = String(contents)
    .replace(
      /^[ \t]*\/\/ Capture React Native soft exceptions before a later hard crash discards them\.\r?\n/gm,
      ''
    )
    .replace(/^[ \t]*NoctaliaSoftExceptionLogger\.install\(this\)[ \t]*\r?\n/gm, '');

  const superOnCreate = /^([ \t]*)super\.onCreate\(\)[ \t]*$/m;
  if (!superOnCreate.test(next)) {
    throw new Error('Unable to locate MainApplication.onCreate().');
  }

  // Registered before `loadReactNative` so the listener is in place for any
  // soft exception raised during React Native startup.
  next = next.replace(superOnCreate, (_line, indent) =>
    [`${indent}super.onCreate()`, `${indent}${INSTALL_COMMENT}`, `${indent}${INSTALL_CALL}`].join(
      '\n'
    )
  );

  return next;
}

module.exports = function withSoftExceptionLogging(config) {
  const packageName = config.android && config.android.package;

  let next = withDangerousMod(config, [
    'android',
    (modConfig) => {
      const sourceRoot = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...packageName.split('.')
      );
      fs.mkdirSync(sourceRoot, { recursive: true });
      fs.writeFileSync(
        path.join(sourceRoot, `${JAVA_CLASS_NAME}.java`),
        buildSoftExceptionLoggerSource(packageName),
        'utf8'
      );
      return modConfig;
    },
  ]);

  next = withMainApplication(next, (modConfig) => {
    if (modConfig.modResults.language !== 'kt') {
      throw new Error('Soft exception logging requires a Kotlin MainApplication.');
    }
    modConfig.modResults.contents = applyMainApplicationInstall(modConfig.modResults.contents);
    return modConfig;
  });

  return next;
};

module.exports.applyMainApplicationInstall = applyMainApplicationInstall;
module.exports.buildSoftExceptionLoggerSource = buildSoftExceptionLoggerSource;
