import type { DreamGuideLanguage, DreamGuideUiCopy } from '@/lib/dreamGuideTypes';

const DREAM_GUIDE_COPY: Record<DreamGuideLanguage, DreamGuideUiCopy> = {
  en: {
    screenTitle: 'Dream guides',
    screenSubtitle: 'Understand your dreams, improve recall and explore Noctalia’s essential themes and symbols.',
    dictionaryTitle: 'Dream symbols dictionary',
    dictionaryBody: 'Looking for one precise image? Search all 150 symbols, meanings, variations, and reflection prompts.',
    dictionaryCta: 'Open the dictionary',
    guideLabel: 'Dream guide',
    practicalLabel: 'Practical guides',
    symbolGuidesLabel: 'Symbol guides',
    essentialsHeading: 'What to remember',
    symbolsHeading: 'Symbols in this guide',
    conclusionHeading: 'Keep in mind',
    readingTime: (minutes) => `${minutes} min read`,
    symbolCount: (count) => `${count} symbols`,
    notFound: 'Guide not found',
  },
  fr: {
    screenTitle: 'Guides des rêves',
    screenSubtitle: 'Comprenez vos rêves, améliorez votre rappel et explorez les thèmes et symboles essentiels de Noctalia.',
    dictionaryTitle: 'Dictionnaire des symboles',
    dictionaryBody: 'Vous cherchez une image précise ? Parcourez les 150 symboles, leurs sens, variantes et questions de réflexion.',
    dictionaryCta: 'Ouvrir le dictionnaire',
    guideLabel: 'Guide des rêves',
    practicalLabel: 'Guides pratiques',
    symbolGuidesLabel: 'Guides des symboles',
    essentialsHeading: 'L’essentiel',
    symbolsHeading: 'Symboles de ce guide',
    conclusionHeading: 'À garder en tête',
    readingTime: (minutes) => `${minutes} min de lecture`,
    symbolCount: (count) => `${count} symboles`,
    notFound: 'Guide introuvable',
  },
  es: {
    screenTitle: 'Guías de sueños',
    screenSubtitle: 'Comprende tus sueños, mejora el recuerdo y explora los temas y símbolos esenciales de Noctalia.',
    dictionaryTitle: 'Diccionario de símbolos',
    dictionaryBody: '¿Buscas una imagen concreta? Explora los 150 símbolos, sus significados, variaciones y preguntas de reflexión.',
    dictionaryCta: 'Abrir el diccionario',
    guideLabel: 'Guía de sueños',
    practicalLabel: 'Guías prácticas',
    symbolGuidesLabel: 'Guías de símbolos',
    essentialsHeading: 'Lo esencial',
    symbolsHeading: 'Símbolos de esta guía',
    conclusionHeading: 'Ten en cuenta',
    readingTime: (minutes) => `${minutes} min de lectura`,
    symbolCount: (count) => `${count} símbolos`,
    notFound: 'Guía no encontrada',
  },
  de: {
    screenTitle: 'Traumratgeber',
    screenSubtitle: 'Verstehen Sie Ihre Träume, verbessern Sie die Erinnerung und entdecken Sie Noctalias wichtigste Themen und Symbole.',
    dictionaryTitle: 'Traumsymbole-Lexikon',
    dictionaryBody: 'Suchen Sie ein bestimmtes Bild? Entdecken Sie 150 Symbole mit Bedeutungen, Varianten und Reflexionsfragen.',
    dictionaryCta: 'Lexikon öffnen',
    guideLabel: 'Traumratgeber',
    practicalLabel: 'Praktische Ratgeber',
    symbolGuidesLabel: 'Symbolratgeber',
    essentialsHeading: 'Das Wichtigste',
    symbolsHeading: 'Symbole in diesem Ratgeber',
    conclusionHeading: 'Wichtig',
    readingTime: (minutes) => `${minutes} Min. Lesezeit`,
    symbolCount: (count) => `${count} Symbole`,
    notFound: 'Ratgeber nicht gefunden',
  },
  it: {
    screenTitle: 'Guide ai sogni',
    screenSubtitle: 'Comprendi i tuoi sogni, migliora il ricordo ed esplora i temi e i simboli essenziali di Noctalia.',
    dictionaryTitle: 'Dizionario dei simboli',
    dictionaryBody: 'Cerchi un’immagine precisa? Esplora 150 simboli con significati, varianti e domande di riflessione.',
    dictionaryCta: 'Apri il dizionario',
    guideLabel: 'Guida ai sogni',
    practicalLabel: 'Guide pratiche',
    symbolGuidesLabel: 'Guide ai simboli',
    essentialsHeading: 'In breve',
    symbolsHeading: 'Simboli in questa guida',
    conclusionHeading: 'Da ricordare',
    readingTime: (minutes) => `${minutes} min di lettura`,
    symbolCount: (count) => `${count} simboli`,
    notFound: 'Guida non trovata',
  },
};

export function getDreamGuideCopy(language: DreamGuideLanguage): DreamGuideUiCopy {
  return DREAM_GUIDE_COPY[language] ?? DREAM_GUIDE_COPY.en;
}
