export const TID = {
  Screen: {
    Onboarding: 'screen.onboarding',
    Recording: 'screen.recording',
    SymbolDetail: 'screen.symbolDetail',
    Journal: 'screen.journal',
    Paywall: 'screen.paywall',
    WeeklyRecap: 'screen.weeklyRecap',
    ResetPassword: 'screen.auth.resetPassword',
    SubscriptionQALab: 'screen.subscription.qaLab',
  },
  Input: {
    SearchDreams: 'input.searchDreams',
    DreamTranscript: 'input.dreamTranscript',
    DreamTitle: 'input.dreamTitle',
    AuthEmail: 'input.auth.email',
    AuthPassword: 'input.auth.password',
    AuthForgotPasswordEmail: 'input.auth.forgotPasswordEmail',
    AuthNewPassword: 'input.auth.newPassword',
    AuthConfirmPassword: 'input.auth.confirmPassword',
  },
  Button: {
    AddDream: 'btn.addDream',
    MockNavHome: 'btn.mockNav.home',
    MockNavJournal: 'btn.mockNav.journal',
    MockNavStats: 'btn.mockNav.stats',
    MockNavSettings: 'btn.mockNav.settings',
    RecordToggle: 'btn.recordToggle',
    SwitchToText: 'btn.recording.switchToText',
    SwitchToVoice: 'btn.recording.switchToVoice',
    InputModeSelect: 'btn.recording.inputMode.select',
    InputModeDismiss: 'btn.recording.inputMode.dismiss',
    InputModeText: 'btn.recording.inputMode.text',
    InputModeVoice: 'btn.recording.inputMode.voice',
    HideRecordingVoiceStatus: 'btn.recording.voiceStatus.hide',
    ShowRecordingVoiceStatus: 'btn.recording.voiceStatus.show',
    ClearDream: 'btn.recording.clearDream',
    MicRationaleAllow: 'btn.recording.micRationale.allow',
    MicRationaleUseText: 'btn.recording.micRationale.useText',
    MicRationaleDismiss: 'btn.recording.micRationale.dismiss',
    SaveDream: 'btn.saveDream',
    NavigateJournal: 'btn.navigateJournal',
    NavigateSettings: 'btn.navigateSettings',
    FilterTheme: 'btn.filterTheme',
    FilterDate: 'btn.filterDate',
    FilterAll: 'btn.filterAll',
    FilterFavorites: 'btn.filterFavorites',
    FilterToDeepen: 'btn.filterToDeepen',
    FilterAnalyzed: 'btn.filterAnalyzed',
    FilterExplored: 'btn.filterExplored',
    FilterRemembered: 'btn.filterRemembered',
    FilterRecurring: 'btn.filterRecurring',
    FilterSearch: 'btn.filterSearch',
    FilterMore: 'btn.filterMore',
    FilterStatusAll: 'btn.filterStatus.all',
    FilterStatusUnanalyzed: 'btn.filterStatus.unanalyzed',
    FilterStatusAnalyzed: 'btn.filterStatus.analyzed',
    FilterStatusExplored: 'btn.filterStatus.explored',
    JournalLayoutCards: 'btn.settings.journalLayout.cards',
    JournalLayoutCompact: 'btn.settings.journalLayout.compact',
    SettingsStreakRiskToggle: 'btn.settings.notifications.streakRisk',
    SettingsInactivityNudgeToggle: 'btn.settings.notifications.inactivityNudge',
    ClearFilters: 'btn.clearFilters',
    AdvancedFiltersClear: 'btn.advancedFilters.clear',
    EmptyClearFilters: 'btn.empty.clearFilters',
    EmptyStartRememberedDream: 'btn.empty.startRememberedDream',
    MockProfile: (profile: string) => `btn.mockProfile.${profile}`,
    MockResetState: 'btn.mock.resetState',
    ExploreDream: 'btn.exploreDream',
    DreamCategory: (id: string) => `btn.dreamCategory.${id}`,
    DreamFreeChat: 'btn.dreamCategory.freeChat',
    AuthSignIn: 'btn.auth.signIn',
    AuthGoogle: 'btn.auth.google',
    AuthApple: 'btn.auth.apple',
    AuthSignUp: 'btn.auth.signUp',
    AuthSignOut: 'btn.auth.signOut',
    AuthResendVerification: 'btn.auth.resendVerification',
    AuthCloseVerification: 'btn.auth.closeVerification',
    AuthTogglePassword: 'btn.auth.togglePassword',
    AuthForgotPassword: 'btn.auth.forgotPassword',
    AuthSendPasswordReset: 'btn.auth.sendPasswordReset',
    AuthCloseForgotPassword: 'btn.auth.closeForgotPassword',
    AuthUpdatePassword: 'btn.auth.updatePassword',
    AuthResetContinue: 'btn.auth.resetContinue',
    AuthResetBackToSignIn: 'btn.auth.resetBackToSignIn',
    FirstDreamAnalyze: 'btn.firstDream.analyze',
    FirstDreamJournal: 'btn.firstDream.journal',
    FirstDreamDismiss: 'btn.firstDream.dismiss',
    RecordingOnboardingNext: 'btn.recording.onboarding.next',
    RecordingOnboardingSkip: 'btn.recording.onboarding.skip',
    RecordingVoiceHintDismiss: 'btn.recording.voiceHint.dismiss',
    RecordingOnboardingRestart: 'btn.recording.onboarding.restart',
    OnboardingBack: 'btn.onboarding.back',
    OnboardingIntroNext: 'btn.onboarding.intro.next',
    OnboardingPath: (id: string) => `btn.onboarding.path.${id}`,
    OnboardingPrimary: 'btn.onboarding.primary',
    OnboardingSkip: 'btn.onboarding.skip',
    OnboardingPrivacy: 'btn.onboarding.privacy',
    OnboardingRetry: 'btn.onboarding.retry',
    OnboardingContinueSession: 'btn.onboarding.continueSession',
    RememberedDreamMetadataToggle: 'btn.recording.remembered.metadata.toggle',
    RememberedDreamDetailsDone: 'btn.recording.remembered.details.done',
    AnalysisOfferPrimary: 'btn.recording.analysisOffer.primary',
    AnalysisOfferJournal: 'btn.recording.analysisOffer.journal',
    AnalysisOfferLater: 'btn.recording.analysisOffer.later',
    UnforgettableDreamYes: 'btn.recording.unforgettableDream.yes',
    UnforgettableDreamTonight: 'btn.recording.unforgettableDream.tonight',
    UnforgettableDreamSkip: 'btn.recording.unforgettableDream.skip',
    RememberedDreamKind: (id: string) => `btn.recording.remembered.kind.${id}`,
    RememberedDreamPeriod: (id: string) => `btn.recording.remembered.period.${id}`,
    RememberedDreamFragment: (id: string) => `btn.recording.remembered.fragment.${id}`,
    RecordingHome: 'btn.recording.home',
    InspirationHeroCta: 'btn.inspiration.heroCta',
    InspirationRitualCta: 'btn.inspiration.ritualCta',
    InspirationRitualVariant: (id: string) => `btn.inspiration.ritual.${id}`,
    HeaderHomeDictionary: 'btn.header.home.dictionary',
    HeaderHomeInspiration: 'btn.header.home.inspiration',
    HeaderStatsPeriod: 'btn.header.stats.period',
    HeaderStatsShare: 'btn.header.stats.share',
    InspirationTipNext: 'btn.inspiration.tipNext',
    InspirationQuickAction: (id: string) => `btn.inspiration.quick.${id}`,
    InspirationPulseCta: 'btn.inspiration.pulseCta',
    InspirationLastDreamChat: 'btn.inspiration.lastDream.chat',
    HomeSleepSounds: 'btn.home.sleepSounds',
    StatsInsightCta: 'btn.stats.insightCta',
    DreamProfileCta: 'btn.stats.dreamProfile.cta',
    DreamProfileUpgradeCta: 'btn.stats.dreamProfile.upgradeCta',
    StatsEmotionsUpgradeCta: 'btn.stats.emotions.upgradeCta',
    StatsThemeTrendUpgradeCta: 'btn.stats.themeTrend.upgradeCta',
    Exploration360Synthesis: 'btn.exploration360.synthesis',
    StatsPeriodOption: (id: string) => `btn.stats.period.${id}`,
    StatsPeriodChip: 'btn.stats.periodChip',
    StatsPeriodReset: 'btn.stats.periodReset',
    StatsMostDiscussedDream: 'btn.stats.mostDiscussedDream',
    AnalyzePromptAnalyze: 'btn.analyzePrompt.analyze',
    AnalyzePromptJournal: 'btn.analyzePrompt.journal',
    FirstValueBackupCta: 'btn.firstValueBackup.cta',
    QuotaLimitCtaGuest: 'btn.quotaLimit.ctaGuest',
    QuotaLimitCtaFree: 'btn.quotaLimit.ctaFree',
    QuotaLimitJournal: 'btn.quotaLimit.journal',
    QuotaLimitResetMock: 'btn.quotaLimit.resetMock',
    PaywallSelectMonthly: 'btn.paywall.selectMonthly',
    PaywallSelectAnnual: 'btn.paywall.selectAnnual',
    PaywallPurchase: 'btn.paywall.purchase',
    PaywallRestore: 'btn.paywall.restore',
    ManageSubscription: 'btn.subscription.manage',
    WeeklyRecapBack: 'btn.weeklyRecap.back',
    WeeklyRecapRecord: 'btn.weeklyRecap.record',
    WeeklyRecapOpenDream: 'btn.weeklyRecap.openDream',
    WeeklyRecapUnlockEmotion: 'btn.weeklyRecap.unlockEmotion',
    PersonalReadingNext: 'btn.inspiration.personalReadingNext',
    PersonalReadingRecap: 'btn.inspiration.personalReadingRecap',
    ImageUpgrade: 'btn.journal.imageUpgrade',
    JournalIllustrate: 'btn.journal.illustrate',
    JournalImageRetry: 'btn.journal.imageRetry',
    PaywallTermsOfUse: 'btn.paywall.termsOfUse',
    PaywallPrivacyPolicy: 'btn.paywall.privacyPolicy',
    PaywallClose: 'btn.paywall.close',
    SubscriptionSettingsCta: 'btn.subscription.settingsCta',
    SubscriptionQaProfile: (profile: string) => `btn.subscription.qa.profile.${profile}`,
    SubscriptionQaScenario: (scenario: string) => `btn.subscription.qa.scenario.${scenario}`,
    SubscriptionQaProbe: 'btn.subscription.qa.probe',
    SubscriptionQaRefresh: 'btn.subscription.qa.refresh',
    SubscriptionQaOpenPaywall: 'btn.subscription.qa.openPaywall',
    EditMetadata: 'btn.editMetadata',
    EditTranscript: 'btn.editTranscript',
    DreamFavorite: 'btn.dream.favorite',
    DreamShare: 'btn.dream.share',
    DreamDelete: 'btn.dream.delete',
    DreamDetailPrimaryCta: 'btn.dream.primaryCta',
    AnalysisStaleCta: 'btn.dream.staleCta',
    JournalIllustrationExpand: 'btn.journal.illustration.expand',
    JournalIllustrationClose: 'btn.journal.illustration.close',
    ShareCopy: 'btn.share.copy',
    ShareClose: 'btn.share.close',
    WhatsNewClose: 'btn.whatsNew.close',
    WhatsNewPrimary: 'btn.whatsNew.primary',
    WhatsNewLater: 'btn.whatsNew.later',
  },
  Tab: {
    Home: 'tab.home',
    Journal: 'tab.journal',
    AddDream: 'tab.addDream',
    Stats: 'tab.stats',
    Settings: 'tab.settings',
  },
  List: {
    Dreams: 'list.dreams',
    DreamItem: (id: number | string) => `dream.item.${id}`,
    SymbolItem: (id: string) => `symbol.item.${id}`,
  },
  Modal: {
    Theme: 'modal.theme',
    DateRange: 'modal.dateRange',
    AdvancedFilters: 'modal.advancedFilters',
    StatsPeriod: 'modal.statsPeriod',
    WhatsNew: 'modal.whatsNew',
    JournalIllustrationFullscreen: 'modal.journal.illustration.fullscreen',
  },
  Component: {
    SearchBar: 'component.searchBar',
    EmailVerificationBanner: 'component.emailVerificationBanner',
    AuthForgotPasswordPanel: 'component.auth.forgotPasswordPanel',
    InspirationPulse: 'component.inspiration.pulse',
    InspirationStreak: 'component.inspiration.streak',
    JournalSortOptions: 'component.journal.sortOptions',
    ReminderOptInCard: 'component.reminderOptIn.card',
    PersonalReading: 'component.inspiration.personalReading',
    InspirationTip: 'component.inspiration.tip',
    RecordingDraftProgress: 'component.recording.draftProgress',
    RecordingActivationInsight: 'component.recording.activationInsight',
    RecordingOnboardingTour: 'component.recording.onboardingTour',
    RecordingVoiceHint: 'component.recording.voiceHint',
    OnboardingIntro: 'component.onboarding.intro',
    OnboardingIntroSignals: 'component.onboarding.introSignals',
    OnboardingPath: 'component.onboarding.path',
    OnboardingError: 'component.onboarding.error',
    UnforgettableDreamPrompt: 'component.recording.unforgettableDreamPrompt',
    RememberedDreamProfileChips: 'component.recording.rememberedProfileChips',
    RecordingVoiceStatus: 'component.recording.voiceStatus',
    StatsInsight: 'component.stats.insight',
    DreamProfileCard: 'component.stats.dreamProfile',
    DreamProfilePlusPreview: 'component.stats.dreamProfile.plusPreview',
    StatsPeriodEmpty: 'component.stats.periodEmpty',
    StatsTypeLegend: 'component.stats.typeLegend',
    StatsTopThemes: 'component.stats.topThemes',
    StatsRhythm: 'component.stats.rhythm',
    StatsRhythmChart: 'component.stats.rhythmChart',
    StatsEmotions: 'component.stats.emotions',
    StatsEmotionsLocked: 'component.stats.emotions.locked',
    StatsEmotionsNotEnough: 'component.stats.emotions.notEnough',
    StatsThemeTrend: 'component.stats.themeTrend',
    StatsThemeTrendChart: 'component.stats.themeTrendChart',
    StatsThemeTrendLegend: 'component.stats.themeTrendLegend',
    StatsThemeTrendLocked: 'component.stats.themeTrend.locked',
    StatsThemeTrendNotEnough: 'component.stats.themeTrend.notEnough',
    Exploration360Panel: 'component.exploration360.panel',
    MetadataCard: 'component.metadataCard',
    TranscriptCard: 'component.transcriptCard',
    JournalIllustration: 'component.journal.illustration',
    AnalysisStaleBanner: 'component.dreamDetail.staleBanner',
    DreamDetailActionCard: 'component.dreamDetail.actionCard',
    FirstValueBackupCard: 'component.firstValueBackup.card',
    WhatsNewCard: 'component.whatsNew.card',
    RememberedDreamMetadata: 'component.recording.remembered.metadata',
  },
  Toast: {
    PaywallSuccess: 'toast.paywall.success',
  },
  Text: {
    AuthEmail: 'text.auth.email',
    AuthEmailVerificationStatus: 'text.auth.emailVerificationStatus',
    AuthForgotPasswordStatus: 'text.auth.forgotPasswordStatus',
    AuthResetPasswordError: 'text.auth.resetPasswordError',
    AnalysisLimitBanner: 'text.analysisLimit',
    ChatLimitBanner: 'text.chat.limit',
    ChatMessageCounter: 'text.chat.messageCounter',
    AnalyzePromptTitle: 'text.analyzePromptTitle',
    PaywallTrialFootnote: 'text.paywall.trialFootnote',
    WeeklyRecapCount: 'text.weeklyRecap.count',
    WeeklyRecapTheme: 'text.weeklyRecap.theme',
    WeeklyRecapSymbol: 'text.weeklyRecap.symbol',
    WeeklyRecapEmotion: 'text.weeklyRecap.emotion',
    PersonalReadingRecurring: 'text.inspiration.personalReading.recurring',
    PersonalReadingNext: 'text.inspiration.personalReading.next',
    PersonalReadingReminder: 'text.inspiration.personalReading.reminder',
    FirstDreamSheetTitle: 'text.firstDream.title',
    QuotaLimitTitle: 'text.quotaLimit.title',
    RecordingVoiceStatusTitle: 'text.recording.voiceStatusTitle',
    UnforgettableDreamPromptTitle: 'text.recording.unforgettableDreamPrompt.title',
    RecordingVoiceStatusDetail: 'text.recording.voiceStatusDetail',
    RecordingVoiceStatusDuration: 'text.recording.voiceStatusDuration',
    RecordingVoiceTranscriptPreview: 'text.recording.voiceTranscriptPreview',
    RecordingFallbackNotice: 'text.recording.fallbackNotice',
    RecordingSaveConfirmation: 'text.recording.saveConfirmation',
    RecordingActivationInsightSummary: 'text.recording.activationInsight.summary',
    RecordingInputMode: (mode: string) => `text.recording.inputMode.${mode}`,
    OnboardingProgress: 'text.onboarding.progress',
    DreamDetailActionTitle: 'text.dreamDetail.actionTitle',
    DreamDetailActionMessage: 'text.dreamDetail.actionMessage',
    DreamDetailActionStep: 'text.dreamDetail.actionStep',
    AnalysisStaleBanner: 'text.dreamDetail.staleBanner',
    FirstValueBackupTitle: 'text.firstValueBackup.title',
    SubscriptionQaActionLabel: 'text.subscription.qa.actionLabel',
    SubscriptionQaAction: 'text.subscription.qa.action',
    SubscriptionQaAuth: 'text.subscription.qa.auth',
    SubscriptionQaMode: 'text.subscription.qa.mode',
    SubscriptionQaPackages: 'text.subscription.qa.packages',
    SubscriptionQaState: (state: string) => `state.subscription.qa.${state}`,
    SubscriptionQaStatus: 'text.subscription.qa.status',
    SubscriptionQaProduct: 'text.subscription.qa.product',
    SubscriptionQaUser: 'text.subscription.qa.user',
  },
  Sheet: {
    QuotaLimit: 'sheet.quotaLimit',
    AnalysisNotice: 'sheet.analysisNotice',
    MicRationale: 'sheet.recording.micRationale',
    OnboardingPrivacy: 'sheet.onboarding.privacy',
    AnalysisOffer: 'sheet.recording.analysisOffer',
    RememberedDreamDetails: 'sheet.recording.remembered.details',
  },
  BottomSheet: {
    PaywallError: 'bottomSheet.paywall.error',
  },
  Chat: {
    Input: 'chat.input.message',
    Send: 'chat.button.send',
    Mic: 'chat.button.mic',
    Loading: 'chat.loading',
    ScreenBlocked: 'chat.screen.blocked',
  },
  Quota: {
    AnalysisValue: 'quota.analysisValue',
    ImageValue: 'quota.imageValue',
    ExplorationValue: 'quota.explorationValue',
    RecordingsValue: 'quota.recordingsValue',
  },
  Stats: {
    TotalChatsValue: 'stats.totalChats',
    DreamsWithChatValue: 'stats.dreamsWithChat',
    AnalyzedDreamsValue: 'stats.analyzedDreams',
  },
} as const;

export type TestIDs = typeof TID;
