export const TID = {
  Screen: {
    Recording: 'screen.recording',
    Journal: 'screen.journal',
    Paywall: 'screen.paywall',
    SubscriptionQALab: 'screen.subscription.qaLab',
  },
  Input: {
    SearchDreams: 'input.searchDreams',
    DreamTranscript: 'input.dreamTranscript',
    DreamTitle: 'input.dreamTitle',
    AuthEmail: 'input.auth.email',
    AuthPassword: 'input.auth.password',
  },
  Button: {
    AddDream: 'btn.addDream',
    MockNavHome: 'btn.mockNav.home',
    MockNavJournal: 'btn.mockNav.journal',
    MockNavStats: 'btn.mockNav.stats',
    MockNavSettings: 'btn.mockNav.settings',
    RecordToggle: 'btn.recordToggle',
    SwitchToText: 'btn.recording.switchToText',
    SwitchToVoice: 'btn.recording.switchToVoice',
    InputModeSelect: 'btn.recording.inputMode.select',
    InputModeText: 'btn.recording.inputMode.text',
    InputModeVoice: 'btn.recording.inputMode.voice',
    HideRecordingVoiceStatus: 'btn.recording.voiceStatus.hide',
    ShowRecordingVoiceStatus: 'btn.recording.voiceStatus.show',
    ClearDream: 'btn.recording.clearDream',
    MicRationaleAllow: 'btn.recording.micRationale.allow',
    MicRationaleUseText: 'btn.recording.micRationale.useText',
    MicRationaleDismiss: 'btn.recording.micRationale.dismiss',
    SaveDream: 'btn.saveDream',
    NavigateJournal: 'btn.navigateJournal',
    NavigateSettings: 'btn.navigateSettings',
    FilterTheme: 'btn.filterTheme',
    FilterDate: 'btn.filterDate',
    FilterFavorites: 'btn.filterFavorites',
    FilterAnalyzed: 'btn.filterAnalyzed',
    FilterExplored: 'btn.filterExplored',
    FilterSearch: 'btn.filterSearch',
    FilterMore: 'btn.filterMore',
    JournalLayoutCards: 'btn.settings.journalLayout.cards',
    JournalLayoutCompact: 'btn.settings.journalLayout.compact',
    ClearFilters: 'btn.clearFilters',
    AdvancedFiltersClear: 'btn.advancedFilters.clear',
    EmptyClearFilters: 'btn.empty.clearFilters',
    EmptyStartRememberedDream: 'btn.empty.startRememberedDream',
    MockProfile: (profile: string) => `btn.mockProfile.${profile}`,
    MockResetState: 'btn.mock.resetState',
    ExploreDream: 'btn.exploreDream',
    DreamCategory: (id: string) => `btn.dreamCategory.${id}`,
    DreamFreeChat: 'btn.dreamCategory.freeChat',
    AuthSignIn: 'btn.auth.signIn',
    AuthGoogle: 'btn.auth.google',
    AuthSignUp: 'btn.auth.signUp',
    AuthSignOut: 'btn.auth.signOut',
    AuthResendVerification: 'btn.auth.resendVerification',
    AuthCloseVerification: 'btn.auth.closeVerification',
    AuthTogglePassword: 'btn.auth.togglePassword',
    FirstDreamAnalyze: 'btn.firstDream.analyze',
    FirstDreamJournal: 'btn.firstDream.journal',
    FirstDreamDismiss: 'btn.firstDream.dismiss',
    RecordingOnboardingNext: 'btn.recording.onboarding.next',
    RecordingOnboardingSkip: 'btn.recording.onboarding.skip',
    RecordingOnboardingChooseText: 'btn.recording.onboarding.chooseText',
    RecordingOnboardingChooseVoice: 'btn.recording.onboarding.chooseVoice',
    RecordingOnboardingRestart: 'btn.recording.onboarding.restart',
    UnforgettableDreamYes: 'btn.recording.unforgettableDream.yes',
    UnforgettableDreamTonight: 'btn.recording.unforgettableDream.tonight',
    UnforgettableDreamSkip: 'btn.recording.unforgettableDream.skip',
    RecordingHome: 'btn.recording.home',
    InspirationHeroCta: 'btn.inspiration.heroCta',
    InspirationRitualCta: 'btn.inspiration.ritualCta',
    InspirationRitualVariant: (id: string) => `btn.inspiration.ritual.${id}`,
    HeaderHomeDictionary: 'btn.header.home.dictionary',
    HeaderHomeInspiration: 'btn.header.home.inspiration',
    HeaderStatsPeriod: 'btn.header.stats.period',
    HeaderStatsShare: 'btn.header.stats.share',
    InspirationTipNext: 'btn.inspiration.tipNext',
    InspirationQuickAction: (id: string) => `btn.inspiration.quick.${id}`,
    InspirationPulseCta: 'btn.inspiration.pulseCta',
    StatsInsightCta: 'btn.stats.insightCta',
    DreamProfileCta: 'btn.stats.dreamProfile.cta',
    DreamProfileUpgradeCta: 'btn.stats.dreamProfile.upgradeCta',
    Exploration360Synthesis: 'btn.exploration360.synthesis',
    StatsPeriodOption: (id: string) => `btn.stats.period.${id}`,
    AnalyzePromptAnalyze: 'btn.analyzePrompt.analyze',
    AnalyzePromptJournal: 'btn.analyzePrompt.journal',
    GuestLimitCta: 'btn.guestLimit.cta',
    FirstValueBackupCta: 'btn.firstValueBackup.cta',
    QuotaLimitCtaGuest: 'btn.quotaLimit.ctaGuest',
    QuotaLimitCtaFree: 'btn.quotaLimit.ctaFree',
    QuotaLimitJournal: 'btn.quotaLimit.journal',
    PaywallSelectMonthly: 'btn.paywall.selectMonthly',
    PaywallSelectAnnual: 'btn.paywall.selectAnnual',
    PaywallPurchase: 'btn.paywall.purchase',
    PaywallRestore: 'btn.paywall.restore',
    PaywallClose: 'btn.paywall.close',
    SubscriptionSettingsCta: 'btn.subscription.settingsCta',
    SubscriptionQaProfile: (profile: string) => `btn.subscription.qa.profile.${profile}`,
    SubscriptionQaScenario: (scenario: string) => `btn.subscription.qa.scenario.${scenario}`,
    SubscriptionQaProbe: 'btn.subscription.qa.probe',
    SubscriptionQaRefresh: 'btn.subscription.qa.refresh',
    SubscriptionQaOpenPaywall: 'btn.subscription.qa.openPaywall',
    EditMetadata: 'btn.editMetadata',
    EditTranscript: 'btn.editTranscript',
    DreamFavorite: 'btn.dream.favorite',
    DreamShare: 'btn.dream.share',
    DreamDelete: 'btn.dream.delete',
    DreamDetailPrimaryCta: 'btn.dream.primaryCta',
    ShareCopy: 'btn.share.copy',
    ShareClose: 'btn.share.close',
  },
  Tab: {
    Home: 'tab.home',
    Journal: 'tab.journal',
    AddDream: 'tab.addDream',
    Stats: 'tab.stats',
    Settings: 'tab.settings',
  },
  List: {
    Dreams: 'list.dreams',
    DreamItem: (id: number | string) => `dream.item.${id}`,
  },
  Modal: {
    Theme: 'modal.theme',
    DateRange: 'modal.dateRange',
    AdvancedFilters: 'modal.advancedFilters',
    StatsPeriod: 'modal.statsPeriod',
  },
  Component: {
    SearchBar: 'component.searchBar',
    EmailVerificationBanner: 'component.emailVerificationBanner',
    InspirationPulse: 'component.inspiration.pulse',
    InspirationTip: 'component.inspiration.tip',
    RecordingDraftProgress: 'component.recording.draftProgress',
    RecordingOnboardingTour: 'component.recording.onboardingTour',
    UnforgettableDreamPrompt: 'component.recording.unforgettableDreamPrompt',
    RecordingVoiceStatus: 'component.recording.voiceStatus',
    StatsInsight: 'component.stats.insight',
    DreamProfileCard: 'component.stats.dreamProfile',
    DreamProfilePlusPreview: 'component.stats.dreamProfile.plusPreview',
    Exploration360Panel: 'component.exploration360.panel',
    MetadataCard: 'component.metadataCard',
    TranscriptCard: 'component.transcriptCard',
    DreamDetailActionCard: 'component.dreamDetail.actionCard',
    FirstValueBackupCard: 'component.firstValueBackup.card',
  },
  Toast: {
    PaywallSuccess: 'toast.paywall.success',
  },
  Text: {
    AuthEmail: 'text.auth.email',
    AuthEmailVerificationStatus: 'text.auth.emailVerificationStatus',
    AnalysisLimitBanner: 'text.analysisLimit',
    ChatLimitBanner: 'text.chat.limit',
    ChatMessageCounter: 'text.chat.messageCounter',
    AnalyzePromptTitle: 'text.analyzePromptTitle',
    FirstDreamSheetTitle: 'text.firstDream.title',
    QuotaLimitTitle: 'text.quotaLimit.title',
    RecordingVoiceStatusTitle: 'text.recording.voiceStatusTitle',
    UnforgettableDreamPromptTitle: 'text.recording.unforgettableDreamPrompt.title',
    RecordingVoiceStatusDetail: 'text.recording.voiceStatusDetail',
    RecordingVoiceStatusDuration: 'text.recording.voiceStatusDuration',
    RecordingFallbackNotice: 'text.recording.fallbackNotice',
    DreamDetailActionTitle: 'text.dreamDetail.actionTitle',
    DreamDetailActionMessage: 'text.dreamDetail.actionMessage',
    DreamDetailActionStep: 'text.dreamDetail.actionStep',
    FirstValueBackupTitle: 'text.firstValueBackup.title',
    SubscriptionQaActionLabel: 'text.subscription.qa.actionLabel',
    SubscriptionQaAction: 'text.subscription.qa.action',
    SubscriptionQaAuth: 'text.subscription.qa.auth',
    SubscriptionQaMode: 'text.subscription.qa.mode',
    SubscriptionQaPackages: 'text.subscription.qa.packages',
    SubscriptionQaState: (state: string) => `state.subscription.qa.${state}`,
    SubscriptionQaStatus: 'text.subscription.qa.status',
    SubscriptionQaProduct: 'text.subscription.qa.product',
    SubscriptionQaUser: 'text.subscription.qa.user',
  },
  Sheet: {
    QuotaLimit: 'sheet.quotaLimit',
    AnalysisNotice: 'sheet.analysisNotice',
    MicRationale: 'sheet.recording.micRationale',
  },
  BottomSheet: {
    PaywallError: 'bottomSheet.paywall.error',
  },
  Chat: {
    Input: 'chat.input.message',
    Send: 'chat.button.send',
    Mic: 'chat.button.mic',
    Loading: 'chat.loading',
    ScreenBlocked: 'chat.screen.blocked',
  },
  Quota: {
    AnalysisValue: 'quota.analysisValue',
    ExplorationValue: 'quota.explorationValue',
    RecordingsValue: 'quota.recordingsValue',
  },
  Stats: {
    TotalChatsValue: 'stats.totalChats',
    DreamsWithChatValue: 'stats.dreamsWithChat',
    AnalyzedDreamsValue: 'stats.analyzedDreams',
  },
} as const;

export type TestIDs = typeof TID;
