export const TID = {
  Screen: {
    Recording: 'screen.recording',
    Journal: 'screen.journal',
    Paywall: 'screen.paywall',
  },
  Input: {
    SearchDreams: 'input.searchDreams',
    DreamTranscript: 'input.dreamTranscript',
    AuthEmail: 'input.auth.email',
    AuthPassword: 'input.auth.password',
  },
  Button: {
    AddDream: 'btn.addDream',
    RecordToggle: 'btn.recordToggle',
    SaveDream: 'btn.saveDream',
    NavigateJournal: 'btn.navigateJournal',
    NavigateSettings: 'btn.navigateSettings',
    FilterTheme: 'btn.filterTheme',
    FilterDate: 'btn.filterDate',
    FilterFavorites: 'btn.filterFavorites',
    FilterAnalyzed: 'btn.filterAnalyzed',
    FilterExplored: 'btn.filterExplored',
    ClearFilters: 'btn.clearFilters',
    MockProfile: (profile: string) => `btn.mockProfile.${profile}`,
    ExploreDream: 'btn.exploreDream',
    DreamCategory: (id: string) => `btn.dreamCategory.${id}`,
    AuthSignIn: 'btn.auth.signIn',
    AuthSignUp: 'btn.auth.signUp',
    AuthSignOut: 'btn.auth.signOut',
    AuthResendVerification: 'btn.auth.resendVerification',
    InspirationHeroCta: 'btn.inspiration.heroCta',
    InspirationRitualCta: 'btn.inspiration.ritualCta',
    InspirationTipNext: 'btn.inspiration.tipNext',
    InspirationQuickAction: (id: string) => `btn.inspiration.quick.${id}`,
    PaywallSelectMonthly: 'btn.paywall.selectMonthly',
    PaywallSelectAnnual: 'btn.paywall.selectAnnual',
    PaywallPurchase: 'btn.paywall.purchase',
    PaywallRestore: 'btn.paywall.restore',
    PaywallClose: 'btn.paywall.close',
  },
  Tab: {
    Home: 'tab.home',
    Journal: 'tab.journal',
    Stats: 'tab.stats',
    Settings: 'tab.settings',
  },
  List: {
    Dreams: 'list.dreams',
    DreamItem: (id: number | string) => `dream.item.${id}`,
  },
  Modal: {
    Theme: 'modal.theme',
    DateRange: 'modal.dateRange',
  },
  Component: {
    SearchBar: 'component.searchBar',
    EmailVerificationBanner: 'component.emailVerificationBanner',
    InspirationTip: 'component.inspiration.tip',
  },
  Toast: {
    PaywallSuccess: 'toast.paywall.success',
  },
  Text: {
    AuthEmail: 'text.auth.email',
    AuthEmailVerificationStatus: 'text.auth.emailVerificationStatus',
    AnalysisLimitBanner: 'text.analysisLimit',
    ChatLimitBanner: 'text.chat.limit',
    AnalyzePromptTitle: 'text.analyzePromptTitle',
  },
  Chat: {
    Input: 'chat.input.message',
    Send: 'chat.button.send',
    ScreenBlocked: 'chat.screen.blocked',
  },
  Quota: {
    AnalysisValue: 'quota.analysisValue',
    ExplorationValue: 'quota.explorationValue',
  },
  Stats: {
    TotalChatsValue: 'stats.totalChats',
    DreamsWithChatValue: 'stats.dreamsWithChat',
    AnalyzedDreamsValue: 'stats.analyzedDreams',
  },
} as const;

export type TestIDs = typeof TID;
