import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';

import { LucidButton, LucidCard, LucidChoiceCard, LucidIconAction, LucidIconTile, LucidPill, LucidScreen } from '@/components/lucid/LucidUI';
import { getLucidPalette, LucidPress, LucidRadius, LucidSpace, LucidType } from '@/constants/lucidTheme';
import { useLucidTrainer } from '@/context/LucidTrainerContext';
import { useTheme } from '@/context/ThemeContext';
import type { LucidExperimentResult, LucidPersonalFactor, LucidTechnique } from '@/lib/lucid/model';
import { closeLucidRoute, LUCID_HOME_HREF } from '@/lib/lucid/routes';

const FACTORS: LucidPersonalFactor[] = ['stress', 'alcohol', 'caffeine_late', 'exercise', 'screen_late', 'sleep_debt', 'unusual_schedule'];
const COPY = {
  en: { eyebrow: 'On waking', title: 'Notice, don’t judge', technique: 'Which practice did you try?', prep: 'How long did you prepare?', minutes: 'minutes', result: 'What do you remember?', none: 'No lucidity', pre_lucid: 'Almost lucid', lucid: 'Lucid', recall: 'How much of the dream remains?', lucidity: 'How aware did you feel?', sleep: 'How did your sleep feel?', factors: 'Anything to keep in mind?', notes: 'A few neutral details', placeholder: 'Optional', outOf: 'out of', save: 'Save morning review', saved: 'Saved offline', incomplete: 'Choose an answer to continue.', next: 'Continue', review: 'Review', back: 'Back', step: 'Step', of: 'of', summary: 'Your observation', context: 'Optional context', noNotes: 'No additional note', stress: 'Stress', alcohol: 'Alcohol', caffeine_late: 'Late caffeine', exercise: 'Exercise', screen_late: 'Late screen', sleep_debt: 'Sleep debt', unusual_schedule: 'Unusual schedule' },
  fr: { eyebrow: 'Au réveil', title: 'Observez, sans juger', technique: 'Quelle pratique avez-vous essayée ?', prep: 'Combien de temps avez-vous préparé ?', minutes: 'minutes', result: 'Que retenez-vous ?', none: 'Pas de lucidité', pre_lucid: 'Presque lucide', lucid: 'Lucide', recall: 'Que reste-t-il du rêve ?', lucidity: 'À quel point étiez-vous conscient·e ?', sleep: 'Comment votre sommeil vous a-t-il semblé ?', factors: 'Quel contexte retenir ?', notes: 'Quelques détails neutres', placeholder: 'Facultatif', outOf: 'sur', save: 'Enregistrer le bilan', saved: 'Enregistré hors ligne', incomplete: 'Choisissez une réponse pour continuer.', next: 'Continuer', review: 'Relire', back: 'Retour', step: 'Étape', of: 'sur', summary: 'Votre observation', context: 'Contexte facultatif', noNotes: 'Aucune note supplémentaire', stress: 'Stress', alcohol: 'Alcool', caffeine_late: 'Caféine tardive', exercise: 'Exercice', screen_late: 'Écran tardif', sleep_debt: 'Dette de sommeil', unusual_schedule: 'Horaire inhabituel' },
  es: { eyebrow: 'Al despertar', title: 'Observa, no juzgues', technique: '¿Qué práctica probaste?', prep: '¿Cuánto te preparaste?', minutes: 'minutos', result: '¿Qué recuerdas?', none: 'Sin lucidez', pre_lucid: 'Casi lúcido', lucid: 'Lúcido', recall: '¿Cuánto queda del sueño?', lucidity: '¿Qué tan consciente te sentiste?', sleep: '¿Cómo sentiste el sueño?', factors: '¿Algo que tener en cuenta?', notes: 'Algunos detalles neutrales', placeholder: 'Opcional', outOf: 'de', save: 'Guardar revisión', saved: 'Guardado sin conexión', incomplete: 'Elige una respuesta para continuar.', next: 'Continuar', review: 'Revisar', back: 'Atrás', step: 'Paso', of: 'de', summary: 'Tu observación', context: 'Contexto opcional', noNotes: 'Sin nota adicional', stress: 'Estrés', alcohol: 'Alcohol', caffeine_late: 'Cafeína tardía', exercise: 'Ejercicio', screen_late: 'Pantalla tardía', sleep_debt: 'Deuda de sueño', unusual_schedule: 'Horario inusual' },
  de: { eyebrow: 'Beim Aufwachen', title: 'Beobachten, nicht bewerten', technique: 'Welche Übung hast du ausprobiert?', prep: 'Wie lange hast du dich vorbereitet?', minutes: 'Minuten', result: 'Woran erinnerst du dich?', none: 'Keine Klarheit', pre_lucid: 'Fast klar', lucid: 'Klar', recall: 'Wie viel vom Traum bleibt?', lucidity: 'Wie bewusst hast du dich gefühlt?', sleep: 'Wie hat sich dein Schlaf angefühlt?', factors: 'Gibt es etwas zu beachten?', notes: 'Einige neutrale Details', placeholder: 'Optional', outOf: 'von', save: 'Morgenrückblick speichern', saved: 'Offline gespeichert', incomplete: 'Wähle eine Antwort, um fortzufahren.', next: 'Weiter', review: 'Prüfen', back: 'Zurück', step: 'Schritt', of: 'von', summary: 'Deine Beobachtung', context: 'Optionaler Kontext', noNotes: 'Keine zusätzliche Notiz', stress: 'Stress', alcohol: 'Alkohol', caffeine_late: 'Spätes Koffein', exercise: 'Bewegung', screen_late: 'Später Bildschirm', sleep_debt: 'Schlafdefizit', unusual_schedule: 'Ungewöhnlicher Rhythmus' },
  it: { eyebrow: 'Al risveglio', title: 'Osserva, non giudicare', technique: 'Quale pratica hai provato?', prep: 'Per quanto tempo ti sei preparato?', minutes: 'minuti', result: 'Cosa ricordi?', none: 'Nessuna lucidità', pre_lucid: 'Quasi lucido', lucid: 'Lucido', recall: 'Quanto resta del sogno?', lucidity: 'Quanto ti sei sentito consapevole?', sleep: 'Come hai percepito il sonno?', factors: 'Qualcosa da tenere a mente?', notes: 'Alcuni dettagli neutrali', placeholder: 'Facoltativo', outOf: 'su', save: 'Salva bilancio', saved: 'Salvato offline', incomplete: 'Scegli una risposta per continuare.', next: 'Continua', review: 'Rivedi', back: 'Indietro', step: 'Passo', of: 'di', summary: 'La tua osservazione', context: 'Contesto facoltativo', noNotes: 'Nessuna nota aggiuntiva', stress: 'Stress', alcohol: 'Alcol', caffeine_late: 'Caffeina tardiva', exercise: 'Esercizio', screen_late: 'Schermo tardivo', sleep_debt: 'Debito di sonno', unusual_schedule: 'Orario insolito' },
} as const;

type MorningStep = 'technique' | 'preparation' | 'result' | 'recall' | 'lucidity' | 'sleep' | 'context' | 'summary';
type LocalCopy = (typeof COPY)[keyof typeof COPY];

export default function LucidMorningScreen() {
  const { content, addExperiment } = useLucidTrainer();
  const copy = COPY[content.locale];
  const [technique, setTechnique] = useState<LucidTechnique | null>(null);
  const [preparationMinutes, setPreparationMinutes] = useState<number | null>(null);
  const [result, setResult] = useState<LucidExperimentResult | null>(null);
  const [lucidityLevel, setLucidityLevel] = useState<number | null>(null);
  const [recallLevel, setRecallLevel] = useState<number | null>(null);
  const [sleepQuality, setSleepQuality] = useState<number | null>(null);
  const [factors, setFactors] = useState<LucidPersonalFactor[]>([]);
  const [notes, setNotes] = useState('');
  const [saving, setSaving] = useState(false);
  const [stepIndex, setStepIndex] = useState(0);
  const steps = useMemo<MorningStep[]>(() => ['technique', 'preparation', 'result', 'recall', ...(result !== null && result !== 'none' ? ['lucidity' as const] : []), 'sleep', 'context', 'summary'], [result]);
  const step = steps[Math.min(stepIndex, steps.length - 1)];
  const answerReady = step === 'technique' ? technique !== null : step === 'preparation' ? preparationMinutes !== null : step === 'result' ? result !== null : step === 'recall' ? recallLevel !== null : step === 'lucidity' ? lucidityLevel !== null : step === 'sleep' ? sleepQuality !== null : true;
  const close = () => closeLucidRoute(router, LUCID_HOME_HREF);
  const goBack = () => stepIndex === 0 ? close() : setStepIndex((value) => Math.max(0, value - 1));
  const goNext = () => { if (answerReady) setStepIndex((value) => Math.min(value + 1, steps.length - 1)); };
  const toggleFactor = (factor: LucidPersonalFactor) => setFactors((items) => items.includes(factor) ? items.filter((item) => item !== factor) : [...items, factor]);
  const save = async () => {
    if (technique === null || preparationMinutes === null || result === null || recallLevel === null || sleepQuality === null) return;
    const resolvedLucidityLevel = result === 'none' ? 0 : lucidityLevel;
    if (resolvedLucidityLevel == null) return;
    setSaving(true);
    try {
      await addExperiment({ technique, preparationMinutes, result, lucidityLevel: resolvedLucidityLevel, recallLevel, sleepQuality, factors, notes: notes.trim() || undefined });
      if (Platform.OS !== 'web') void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
      Alert.alert(copy.saved, content.morningReview.saveOfflineNote, [{ text: content.chrome.common.done, onPress: close }]);
    } finally { setSaving(false); }
  };

  return <LucidScreen eyebrow={`${copy.step} ${stepIndex + 1} ${copy.of} ${steps.length}`} title={step === 'summary' ? copy.summary : copy.title} subtitle={step === 'context' ? copy.context : undefined} trailing={<LucidIconAction label={stepIndex === 0 ? content.chrome.common.cancel : copy.back} icon={stepIndex === 0 ? 'close' : 'arrow-back'} onPress={goBack} />} testID="lucid-morning">
    {step === 'technique' ? <ChoiceStep title={copy.technique} groupLabel={copy.technique} choices={(['mild', 'ssild', 'wbtb'] as const).map((item) => ({ label: content.programs[item].title, selected: technique === item, onPress: () => setTechnique(item), icon: item === 'mild' ? 'moon' : item === 'ssild' ? 'sparkles' : 'alarm' }))} /> : null}
    {step === 'preparation' ? <ChoiceStep title={copy.prep} groupLabel={copy.prep} choices={[0, 5, 10, 20, 30].map((value) => ({ label: `${value} ${copy.minutes}`, selected: preparationMinutes === value, onPress: () => setPreparationMinutes(value), icon: 'time' }))} /> : null}
    {step === 'result' ? <ChoiceStep title={copy.result} groupLabel={copy.result} choices={(['none', 'pre_lucid', 'lucid'] as const).map((item) => ({ label: copy[item], selected: result === item, onPress: () => setResult(item), icon: item === 'none' ? 'cloudy-night' : item === 'pre_lucid' ? 'moon' : 'sparkles' }))} /> : null}
    {step === 'recall' ? <Score title={copy.recall} outOf={copy.outOf} value={recallLevel} onChange={setRecallLevel} /> : null}
    {step === 'lucidity' ? <Score title={copy.lucidity} outOf={copy.outOf} value={lucidityLevel} onChange={setLucidityLevel} /> : null}
    {step === 'sleep' ? <Score title={copy.sleep} outOf={copy.outOf} value={sleepQuality} onChange={setSleepQuality} /> : null}
    {step === 'context' ? <ContextStep copy={copy} factors={factors} notes={notes} onNotesChange={setNotes} onToggleFactor={toggleFactor} /> : null}
    {step === 'summary' ? <Summary copy={copy} content={content} technique={technique} preparationMinutes={preparationMinutes} result={result} recallLevel={recallLevel} lucidityLevel={lucidityLevel} sleepQuality={sleepQuality} factors={factors} notes={notes} /> : null}
    {step === 'summary' ? <LucidButton label={copy.save} icon="checkmark" loading={saving} onPress={() => void save()} testID="lucid-morning-save" /> : <LucidButton label={step === 'context' ? copy.review : copy.next} icon="arrow-forward" disabled={!answerReady} disabledReason={copy.incomplete} onPress={goNext} testID="lucid-morning-next" />}
  </LucidScreen>;
}

function ChoiceStep({ title, groupLabel, choices }: { title: string; groupLabel: string; choices: { label: string; selected: boolean; onPress: () => void; icon: 'moon' | 'sparkles' | 'alarm' | 'time' | 'cloudy-night' }[] }) {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  return <View style={styles.step}><View style={styles.prompt}><LucidIconTile icon="sunny" tone="amber" size="lg" /><Text accessibilityRole="header" style={[styles.promptTitle, { color: palette.text }]}>{title}</Text></View><View accessibilityRole="radiogroup" accessibilityLabel={groupLabel} style={styles.choiceList}>{choices.map((choice) => <LucidChoiceCard key={choice.label} title={choice.label} selected={choice.selected} onPress={choice.onPress} icon={choice.icon} />)}</View></View>;
}

function ContextStep({ copy, factors, notes, onNotesChange, onToggleFactor }: { copy: LocalCopy; factors: LucidPersonalFactor[]; notes: string; onNotesChange: (notes: string) => void; onToggleFactor: (factor: LucidPersonalFactor) => void }) {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  return <View style={styles.step}><View style={styles.prompt}><LucidIconTile icon="leaf" tone="neutral" size="lg" /><Text accessibilityRole="header" style={[styles.promptTitle, { color: palette.text }]}>{copy.factors}</Text></View><View style={styles.factorList}>{FACTORS.map((factor) => <SelectChip key={factor} role="checkbox" label={copy[factor]} selected={factors.includes(factor)} onPress={() => onToggleFactor(factor)} />)}</View><Text style={[styles.fieldTitle, { color: palette.text }]}>{copy.notes}</Text><TextInput accessibilityLabel={copy.notes} multiline maxLength={4000} onChangeText={onNotesChange} placeholder={copy.placeholder} placeholderTextColor={palette.textMuted} style={[styles.notes, { backgroundColor: palette.surface, borderColor: palette.borderInteractive, color: palette.text }]} textAlignVertical="top" value={notes} /></View>;
}

function Summary({ copy, content, technique, preparationMinutes, result, recallLevel, lucidityLevel, sleepQuality, factors, notes }: { copy: LocalCopy; content: ReturnType<typeof useLucidTrainer>['content']; technique: LucidTechnique | null; preparationMinutes: number | null; result: LucidExperimentResult | null; recallLevel: number | null; lucidityLevel: number | null; sleepQuality: number | null; factors: LucidPersonalFactor[]; notes: string }) {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  const rows = [[copy.technique, technique ? content.programs[technique].title : '—'], [copy.prep, preparationMinutes === null ? '—' : `${preparationMinutes} ${copy.minutes}`], [copy.result, result ? copy[result] : '—'], [copy.recall, recallLevel === null ? '—' : `${recallLevel} / 5`], ...(result !== null && result !== 'none' ? [[copy.lucidity, lucidityLevel === null ? '—' : `${lucidityLevel} / 5`]] : []), [copy.sleep, sleepQuality === null ? '—' : `${sleepQuality} / 5`]];
  return <LucidCard accent="amber"><View style={styles.summaryTop}><LucidIconTile icon={result === 'lucid' ? 'sparkles' : 'sunny'} tone="amber" size="lg" /><Text style={[styles.summaryTitle, { color: palette.text }]}>{result === 'none' ? content.morningReview.neutralOutcome : copy.summary}</Text></View>{rows.map(([label, value]) => <View key={label} style={[styles.summaryRow, { borderBottomColor: palette.border }]}><Text style={[styles.summaryLabel, { color: palette.textSecondary }]}>{label}</Text><Text style={[styles.summaryValue, { color: palette.text }]}>{value}</Text></View>)}<View style={styles.summaryContext}><Text style={[styles.summaryNote, { color: palette.textSecondary }]}>{factors.length ? factors.map((factor) => copy[factor]).join(' · ') : copy.context}</Text>{notes.trim() ? <Text style={[styles.summaryNote, { color: palette.textSecondary }]}>{notes.trim()}</Text> : <Text style={[styles.summaryNote, { color: palette.textSecondary }]}>{copy.noNotes}</Text>}</View></LucidCard>;
}

function SelectChip({ label, selected, onPress, role = 'radio' }: { label: string; selected: boolean; onPress: () => void; role?: 'radio' | 'checkbox' }) {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  return <Pressable accessibilityRole={role} accessibilityLabel={label} accessibilityState={{ checked: selected, selected }} onPress={onPress} style={({ pressed }) => [styles.chip, { backgroundColor: selected ? palette.accentSoft : palette.surfaceRaised, borderColor: selected ? palette.accent : palette.borderInteractive, opacity: pressed ? LucidPress.opacity : 1 }]}><Text style={[styles.chipText, { color: selected ? palette.accentOn : palette.textSecondary }]}>{label}</Text></Pressable>;
}

function Score({ title, outOf, value, onChange }: { title: string; outOf: string; value: number | null; onChange: (value: number) => void }) {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode); const { fontScale, width } = useWindowDimensions(); const compact = width < 380 || fontScale >= 1.3;
  return <View style={styles.step}><View style={styles.prompt}><LucidIconTile icon="pulse" tone="accent" size="lg" /><Text accessibilityRole="header" style={[styles.promptTitle, { color: palette.text }]}>{title}</Text><LucidPill label={value === null ? '—' : `${value} / 5`} tone={value !== null && value >= 4 ? 'accent' : 'neutral'} /></View><View accessibilityRole="radiogroup" accessibilityLabel={title} style={[styles.scoreRow, compact && styles.scoreRowCompact]}>{[0, 1, 2, 3, 4, 5].map((score) => <Pressable key={score} accessibilityRole="radio" accessibilityLabel={`${title}, ${score} ${outOf} 5`} accessibilityState={{ checked: score === value, selected: score === value }} onPress={() => onChange(score)} style={({ pressed }) => [styles.score, compact && styles.scoreCompact, { backgroundColor: score === value ? palette.accent : palette.surfaceRaised, opacity: pressed ? LucidPress.opacity : 1 }]}><Text style={[styles.scoreText, { color: score === value ? palette.backgroundDeep : palette.textSecondary }]}>{score}</Text></Pressable>)}</View></View>;
}

const styles = StyleSheet.create({ step: { gap: LucidSpace.lg }, prompt: { alignItems: 'center', gap: LucidSpace.md, paddingVertical: LucidSpace.lg }, promptTitle: { fontFamily: 'Fraunces_500Medium', fontSize: LucidType.h2[0], lineHeight: LucidType.h2[1], textAlign: 'center' }, choiceList: { gap: LucidSpace.sm }, factorList: { flexDirection: 'row', flexWrap: 'wrap', gap: LucidSpace.sm }, fieldTitle: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.body[0], lineHeight: LucidType.body[1] }, chip: { minHeight: 44, justifyContent: 'center', borderRadius: LucidRadius.md, borderWidth: 1, paddingHorizontal: LucidSpace.md, paddingVertical: LucidSpace.sm }, chipText: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.overline[0], lineHeight: LucidType.overline[1] }, scoreRow: { flexDirection: 'row', gap: LucidSpace.sm }, scoreRowCompact: { flexWrap: 'wrap' }, score: { flex: 1, minWidth: 44, minHeight: 52, borderRadius: LucidRadius.lg, alignItems: 'center', justifyContent: 'center' }, scoreCompact: { flexBasis: '30%' }, scoreText: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.body[0], lineHeight: LucidType.body[1] }, notes: { minHeight: 120, borderRadius: LucidRadius.lg, borderWidth: 1, padding: LucidSpace.lg, fontFamily: 'SpaceGrotesk_400Regular', fontSize: LucidType.bodySm[0], lineHeight: LucidType.bodySm[1] }, summaryTop: { alignItems: 'center', gap: LucidSpace.md }, summaryTitle: { fontFamily: 'Fraunces_500Medium', fontSize: LucidType.h3[0], lineHeight: LucidType.h3[1], textAlign: 'center' }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', gap: LucidSpace.md, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: LucidSpace.sm }, summaryLabel: { flex: 1, fontFamily: 'SpaceGrotesk_500Medium', fontSize: LucidType.caption[0], lineHeight: LucidType.caption[1] }, summaryValue: { flex: 1, fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.caption[0], lineHeight: LucidType.caption[1], textAlign: 'right' }, summaryContext: { gap: LucidSpace.sm }, summaryNote: { fontFamily: 'SpaceGrotesk_400Regular', fontSize: LucidType.caption[0], lineHeight: LucidType.caption[1] } });
