import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { LucidButton, LucidCard, LucidIconAction, LucidIconTile, LucidPill, LucidScreen } from '@/components/lucid/LucidUI';
import { getLucidPalette, LucidPress, LucidRadius, LucidSpace, LucidType } from '@/constants/lucidTheme';
import { useLucidTrainer } from '@/context/LucidTrainerContext';
import { useTheme } from '@/context/ThemeContext';
import type { LucidExperimentResult, LucidPersonalFactor, LucidTechnique } from '@/lib/lucid/model';
import { closeLucidRoute, LUCID_HOME_HREF } from '@/lib/lucid/routes';

const FACTORS: LucidPersonalFactor[] = ['stress', 'alcohol', 'caffeine_late', 'exercise', 'screen_late', 'sleep_debt', 'unusual_schedule'];
const COPY = {
  en: { eyebrow: 'On waking', title: 'Notice, don’t judge', technique: 'Technique', prep: 'Preparation', minutes: 'minutes', result: 'Result', none: 'No lucidity', pre_lucid: 'Almost lucid', lucid: 'Lucid', recall: 'Dream recall', lucidity: 'Lucidity', sleep: 'Sleep quality', factors: 'Personal factors', notes: 'Optional notes', placeholder: 'A few neutral details…', outOf: 'out of', save: 'Save morning review', saved: 'Saved offline', incomplete: 'Still to answer:', stress: 'Stress', alcohol: 'Alcohol', caffeine_late: 'Late caffeine', exercise: 'Exercise', screen_late: 'Late screen', sleep_debt: 'Sleep debt', unusual_schedule: 'Unusual schedule' },
  fr: { eyebrow: 'Au réveil', title: 'Observez, sans juger', technique: 'Technique', prep: 'Préparation', minutes: 'minutes', result: 'Résultat', none: 'Pas de lucidité', pre_lucid: 'Presque lucide', lucid: 'Lucide', recall: 'Rappel du rêve', lucidity: 'Lucidité', sleep: 'Qualité du sommeil', factors: 'Facteurs personnels', notes: 'Notes facultatives', placeholder: 'Quelques détails neutres…', outOf: 'sur', save: 'Enregistrer le bilan', saved: 'Enregistré hors ligne', incomplete: 'À renseigner :', stress: 'Stress', alcohol: 'Alcool', caffeine_late: 'Caféine tardive', exercise: 'Exercice', screen_late: 'Écran tardif', sleep_debt: 'Dette de sommeil', unusual_schedule: 'Horaire inhabituel' },
  es: { eyebrow: 'Al despertar', title: 'Observa, no juzgues', technique: 'Técnica', prep: 'Preparación', minutes: 'minutos', result: 'Resultado', none: 'Sin lucidez', pre_lucid: 'Casi lúcido', lucid: 'Lúcido', recall: 'Recuerdo', lucidity: 'Lucidez', sleep: 'Calidad del sueño', factors: 'Factores personales', notes: 'Notas opcionales', placeholder: 'Algunos detalles neutrales…', outOf: 'de', save: 'Guardar revisión', saved: 'Guardado sin conexión', incomplete: 'Falta responder:', stress: 'Estrés', alcohol: 'Alcohol', caffeine_late: 'Cafeína tardía', exercise: 'Ejercicio', screen_late: 'Pantalla tardía', sleep_debt: 'Deuda de sueño', unusual_schedule: 'Horario inusual' },
  de: { eyebrow: 'Beim Aufwachen', title: 'Beobachten, nicht bewerten', technique: 'Technik', prep: 'Vorbereitung', minutes: 'Minuten', result: 'Ergebnis', none: 'Keine Klarheit', pre_lucid: 'Fast klar', lucid: 'Klar', recall: 'Traumerinnerung', lucidity: 'Klarheit', sleep: 'Schlafqualität', factors: 'Persönliche Faktoren', notes: 'Optionale Notizen', placeholder: 'Einige neutrale Details…', outOf: 'von', save: 'Morgenrückblick speichern', saved: 'Offline gespeichert', incomplete: 'Noch offen:', stress: 'Stress', alcohol: 'Alkohol', caffeine_late: 'Spätes Koffein', exercise: 'Bewegung', screen_late: 'Später Bildschirm', sleep_debt: 'Schlafdefizit', unusual_schedule: 'Ungewöhnlicher Rhythmus' },
  it: { eyebrow: 'Al risveglio', title: 'Osserva, non giudicare', technique: 'Tecnica', prep: 'Preparazione', minutes: 'minuti', result: 'Risultato', none: 'Nessuna lucidità', pre_lucid: 'Quasi lucido', lucid: 'Lucido', recall: 'Ricordo', lucidity: 'Lucidità', sleep: 'Qualità del sonno', factors: 'Fattori personali', notes: 'Note facoltative', placeholder: 'Alcuni dettagli neutrali…', outOf: 'su', save: 'Salva bilancio', saved: 'Salvato offline', incomplete: 'Ancora da indicare:', stress: 'Stress', alcohol: 'Alcol', caffeine_late: 'Caffeina tardiva', exercise: 'Esercizio', screen_late: 'Schermo tardivo', sleep_debt: 'Debito di sonno', unusual_schedule: 'Orario insolito' },
} as const;

export default function LucidMorningScreen() {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  const { content, addExperiment } = useLucidTrainer(); const copy = COPY[content.locale];
  // Every answer starts empty: a morning review must only ever contain what the
  // user actually reported, since it is persisted, synced and fed to the coach.
  const [technique, setTechnique] = useState<LucidTechnique | null>(null); const [preparationMinutes, setPreparationMinutes] = useState<number | null>(null); const [result, setResult] = useState<LucidExperimentResult | null>(null); const [lucidityLevel, setLucidityLevel] = useState<number | null>(null); const [recallLevel, setRecallLevel] = useState<number | null>(null); const [sleepQuality, setSleepQuality] = useState<number | null>(null); const [factors, setFactors] = useState<LucidPersonalFactor[]>([]); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  const missing = ([technique === null ? copy.technique : null, preparationMinutes === null ? copy.prep : null, result === null ? copy.result : null, recallLevel === null ? copy.recall : null, result !== null && result !== 'none' && lucidityLevel === null ? copy.lucidity : null, sleepQuality === null ? copy.sleep : null] as (string | null)[]).filter((label): label is string => label !== null);
  const toggleFactor = (factor: LucidPersonalFactor) => setFactors((items) => items.includes(factor) ? items.filter((item) => item !== factor) : [...items, factor]);
  const close = () => closeLucidRoute(router, LUCID_HOME_HREF);
  // Le bilan du matin est la validation la plus rare de l'app, et consigner un
  // rêve lucide en est le seul moment de célébration : il mérite le retour que
  // le corps perçoit sans regarder. Jamais seul — l'alerte reste.
  const save = async () => { if (technique === null || preparationMinutes === null || result === null || recallLevel === null || sleepQuality === null) return; setSaving(true); try { await addExperiment({ technique, preparationMinutes, result, lucidityLevel: result === 'none' ? 0 : lucidityLevel ?? 0, recallLevel, sleepQuality, factors, notes: notes.trim() || undefined }); if (Platform.OS !== 'web') void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {}); Alert.alert(copy.saved, content.morningReview.saveOfflineNote, [{ text: content.chrome.common.done, onPress: close }]); } finally { setSaving(false); } };
  return (
    <LucidScreen eyebrow={copy.eyebrow} title={copy.title} subtitle={content.morningReview.intro} trailing={<LucidIconAction label={content.chrome.common.cancel} icon="close" onPress={close} />} testID="lucid-morning">
      <LucidCard accent="amber"><View style={styles.sun}><LucidIconTile icon="sunny" tone="amber" size="lg" /><Text style={[styles.neutral, { color: palette.text }]}>{content.morningReview.neutralOutcome}</Text></View></LucidCard>
      <FieldTitle text={copy.technique} />
      {/* Trois groupes exclusifs — un seul choix chacun — donc `radio` dans un conteneur `radiogroup` nommé. Seuls les facteurs personnels se cumulent, et restent des cases à cocher. */}
      <View accessibilityRole="radiogroup" accessibilityLabel={copy.technique} style={styles.row}>{(['mild', 'ssild', 'wbtb'] as const).map((item) => <SelectChip key={item} label={content.programs[item].title} selected={technique === item} onPress={() => setTechnique(item)} />)}</View>
      <FieldTitle text={copy.prep} /><View accessibilityRole="radiogroup" accessibilityLabel={copy.prep} style={styles.row}>{[0, 5, 10, 20, 30].map((value) => <SelectChip key={value} label={`${value} ${copy.minutes}`} selected={preparationMinutes === value} onPress={() => setPreparationMinutes(value)} />)}</View>
      <FieldTitle text={copy.result} /><View accessibilityRole="radiogroup" accessibilityLabel={copy.result} style={styles.row}>{(['none', 'pre_lucid', 'lucid'] as const).map((item) => <SelectChip key={item} label={copy[item]} selected={result === item} onPress={() => setResult(item)} />)}</View>
      <Score title={copy.recall} outOf={copy.outOf} value={recallLevel} onChange={setRecallLevel} />
      {result !== null && result !== 'none' ? <Score title={copy.lucidity} outOf={copy.outOf} value={lucidityLevel} onChange={setLucidityLevel} /> : null}
      <Score title={copy.sleep} outOf={copy.outOf} value={sleepQuality} onChange={setSleepQuality} />
      <FieldTitle text={copy.factors} /><View style={styles.row}>{FACTORS.map((factor) => <SelectChip key={factor} role="checkbox" label={copy[factor]} selected={factors.includes(factor)} onPress={() => toggleFactor(factor)} />)}</View>
      <FieldTitle text={copy.notes} /><TextInput accessibilityLabel={copy.notes} multiline maxLength={4000} onChangeText={setNotes} placeholder={copy.placeholder} placeholderTextColor={palette.textMuted} style={[styles.notes, { backgroundColor: palette.surface, borderColor: palette.borderInteractive, color: palette.text }]} textAlignVertical="top" value={notes} />
      <LucidButton label={copy.save} icon="checkmark" loading={saving} disabled={missing.length > 0} disabledReason={`${copy.incomplete} ${missing.join(', ')}`} onPress={() => void save()} testID="lucid-morning-save" />
    </LucidScreen>
  );
}

function FieldTitle({ text }: { text: string }) { const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode); return <Text style={[styles.fieldTitle, { color: palette.text }]}>{text}</Text>; }
function SelectChip({ label, selected, onPress, role = 'radio' }: { label: string; selected: boolean; onPress: () => void; role?: 'radio' | 'checkbox' }) { const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode); return <Pressable accessibilityRole={role} accessibilityState={{ checked: selected, selected }} onPress={onPress} style={({ pressed }) => [styles.chip, { backgroundColor: selected ? palette.accentSoft : palette.surfaceRaised, borderColor: selected ? palette.accent : palette.borderInteractive, opacity: pressed ? LucidPress.opacity : 1 }]}><Text style={[styles.chipText, { color: selected ? palette.accentOn : palette.textSecondary }]}>{label}</Text></Pressable>; }
// Six boutons qui s'annonçaient « 0, bouton radio » … « 5, bouton radio » : on
// savait noter, jamais quoi. Le conteneur porte le titre de l'échelle et chaque
// bouton le répète — « Qualité du sommeil, 3 sur 5 ».
function Score({ title, outOf, value, onChange }: { title: string; outOf: string; value: number | null; onChange: (value: number) => void }) { const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode); return <View style={styles.scoreBlock}><View style={styles.scoreTop}><FieldTitle text={title} /><LucidPill label={value === null ? '—' : `${value} / 5`} tone={value !== null && value >= 4 ? 'accent' : 'neutral'} /></View><View accessibilityRole="radiogroup" accessibilityLabel={title} style={styles.scoreRow}>{[0,1,2,3,4,5].map((score) => <Pressable key={score} accessibilityRole="radio" accessibilityLabel={`${title}, ${score} ${outOf} 5`} accessibilityState={{ checked: score === value, selected: score === value }} onPress={() => onChange(score)} style={({ pressed }) => [styles.score, { backgroundColor: score === value ? palette.accent : palette.surfaceRaised, opacity: pressed ? LucidPress.opacity : 1 }]}><Text style={[styles.scoreText, { color: score === value ? palette.backgroundDeep : palette.textSecondary }]}>{score}</Text></Pressable>)}</View></View>; }
const styles = StyleSheet.create({ sun: { alignItems: 'center', gap: LucidSpace.md }, neutral: { fontFamily: 'Fraunces_500Medium', fontSize: LucidType.h3[0], lineHeight: LucidType.h3[1], textAlign: 'center' }, fieldTitle: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.body[0], lineHeight: LucidType.body[1] }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: LucidSpace.sm }, chip: { minHeight: 44, justifyContent: 'center', borderRadius: LucidRadius.md, borderWidth: 1, paddingHorizontal: LucidSpace.md, paddingVertical: LucidSpace.sm }, chipText: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.overline[0], lineHeight: LucidType.overline[1] }, scoreBlock: { gap: LucidSpace.md }, scoreTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, scoreRow: { flexDirection: 'row', gap: LucidSpace.sm }, score: { flex: 1, minHeight: 44, paddingVertical: LucidSpace.sm, borderRadius: LucidRadius.md, alignItems: 'center', justifyContent: 'center' }, scoreText: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.caption[0], lineHeight: LucidType.caption[1] }, notes: { minHeight: 120, borderRadius: LucidRadius.lg, borderWidth: 1, padding: LucidSpace.lg, fontFamily: 'SpaceGrotesk_400Regular', fontSize: LucidType.bodySm[0], lineHeight: LucidType.bodySm[1] } });
