import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';

import { LucidButton, LucidCard, LucidIconAction, LucidIconTile, LucidMetric, LucidPill, LucidScreen } from '@/components/lucid/LucidUI';
import { getLucidPalette, LucidRadius, LucidSpace, LucidType } from '@/constants/lucidTheme';
import { useLucidTrainer } from '@/context/LucidTrainerContext';
import { useTheme } from '@/context/ThemeContext';
import { useLucidNow } from '@/hooks/useLucidNow';
import { getLucidLocalDateKey } from '@/lib/lucid/calendar';
import { buildLucidWeeklyReview } from '@/lib/lucid/progress';
import { closeLucidRoute, LUCID_HOME_HREF } from '@/lib/lucid/routes';

const COPY = {
  en: { protect_sleep: 'Your notes suggest protecting sleep first. Skip disruptive techniques tonight.', start_first_session: 'Start gently with the first MILD session.', complete_preparation: 'A short, complete preparation is the most useful next step.', strengthen_recall: 'Focus on recall and write a few fragments on waking.', repeat_best_method: 'Repeat the method that has worked best for you.', keep_routine: 'Your routine is consistent. Keep it simple this week.', try_another_method: 'There is not enough signal yet; try another method without changing sleep length.', eyebrow: 'Weekly adaptation', title: 'Review the week gently', practice: 'practice days', recall: 'recall days', lucid: 'lucid dreams', recommendation: 'Suggested next focus', notes: 'What helped or disturbed sleep?', save: 'Save weekly review', saved: 'Weekly review saved', continue: 'Continue', review: 'Review', back: 'Back', step: 'Step', of: 'of', summary: 'Your week at a glance', noNotes: 'No additional note' },
  fr: { protect_sleep: 'Vos notes suggèrent de protéger le sommeil en priorité. Évitez les techniques perturbatrices ce soir.', start_first_session: 'Commencez doucement par la première séance MILD.', complete_preparation: 'Une préparation courte et complète est la prochaine étape la plus utile.', strengthen_recall: 'Concentrez-vous sur le rappel et notez quelques fragments au réveil.', repeat_best_method: 'Répétez la méthode qui vous a le mieux convenu.', keep_routine: 'Votre routine est régulière. Gardez-la simple cette semaine.', try_another_method: 'Le signal est encore faible ; essayez une autre méthode sans réduire votre sommeil.', eyebrow: 'Adaptation hebdomadaire', title: 'Relisez la semaine avec douceur', practice: 'jours de pratique', recall: 'jours de rappel', lucid: 'rêves lucides', recommendation: 'Prochain axe suggéré', notes: 'Qu’est-ce qui a aidé ou perturbé le sommeil ?', save: 'Enregistrer le bilan', saved: 'Bilan hebdomadaire enregistré', continue: 'Continuer', review: 'Relire', back: 'Retour', step: 'Étape', of: 'sur', summary: 'Votre semaine en un regard', noNotes: 'Aucune note supplémentaire' },
  es: { protect_sleep: 'Tus notas sugieren proteger primero el sueño.', start_first_session: 'Empieza suavemente con la primera sesión MILD.', complete_preparation: 'Una preparación breve y completa es el siguiente paso útil.', strengthen_recall: 'Concéntrate en recordar y anota algunos fragmentos al despertar.', repeat_best_method: 'Repite el método que mejor te ha funcionado.', keep_routine: 'Tu rutina es constante. Mantenla sencilla esta semana.', try_another_method: 'Aún hay poca señal; prueba otro método sin reducir el sueño.', eyebrow: 'Adaptación semanal', title: 'Revisa la semana con calma', practice: 'días de práctica', recall: 'días de recuerdo', lucid: 'sueños lúcidos', recommendation: 'Próximo foco sugerido', notes: '¿Qué ayudó o alteró el sueño?', save: 'Guardar revisión semanal', saved: 'Revisión guardada', continue: 'Continuar', review: 'Revisar', back: 'Atrás', step: 'Paso', of: 'de', summary: 'Tu semana de un vistazo', noNotes: 'Sin nota adicional' },
  de: { protect_sleep: 'Deine Notizen sprechen dafür, zuerst den Schlaf zu schützen.', start_first_session: 'Beginne sanft mit der ersten MILD-Einheit.', complete_preparation: 'Eine kurze, vollständige Vorbereitung ist der beste nächste Schritt.', strengthen_recall: 'Konzentriere dich auf Erinnerung und notiere morgens Fragmente.', repeat_best_method: 'Wiederhole die Methode, die am besten funktionierte.', keep_routine: 'Deine Routine ist stabil. Halte sie diese Woche einfach.', try_another_method: 'Noch wenig Signal: Teste eine andere Methode, ohne Schlaf zu kürzen.', eyebrow: 'Wöchentliche Anpassung', title: 'Die Woche sanft betrachten', practice: 'Übungstage', recall: 'Erinnerungstage', lucid: 'Klarträume', recommendation: 'Nächster Fokus', notes: 'Was hat Schlaf geholfen oder gestört?', save: 'Wochenrückblick speichern', saved: 'Wochenrückblick gespeichert', continue: 'Weiter', review: 'Prüfen', back: 'Zurück', step: 'Schritt', of: 'von', summary: 'Deine Woche im Überblick', noNotes: 'Keine zusätzliche Notiz' },
  it: { protect_sleep: 'Le tue note suggeriscono di proteggere prima il sonno.', start_first_session: 'Inizia con calma dalla prima sessione MILD.', complete_preparation: 'Una preparazione breve e completa è il prossimo passo utile.', strengthen_recall: 'Concentrati sul ricordo e annota alcuni frammenti al risveglio.', repeat_best_method: 'Ripeti il metodo che ha funzionato meglio.', keep_routine: 'La tua routine è costante. Mantienila semplice questa settimana.', try_another_method: 'Ci sono ancora pochi dati; prova un altro metodo senza ridurre il sonno.', eyebrow: 'Adattamento settimanale', title: 'Rivedi la settimana con calma', practice: 'giorni di pratica', recall: 'giorni di ricordo', lucid: 'sogni lucidi', recommendation: 'Prossimo focus suggerito', notes: 'Cosa ha aiutato o disturbato il sonno?', save: 'Salva bilancio settimanale', saved: 'Bilancio salvato', continue: 'Continua', review: 'Rivedi', back: 'Indietro', step: 'Passo', of: 'di', summary: 'La tua settimana in breve', noNotes: 'Nessuna nota aggiuntiva' },
} as const;

export default function LucidWeeklyScreen() {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  const { state, content, saveWeeklyReview } = useLucidTrainer(); const copy = COPY[content.locale];
  const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [step, setStep] = useState(0);
  const now = useLucidNow(); const { fontScale, width } = useWindowDimensions(); const compact = width < 380 || fontScale >= 1.3;
  const review = useMemo(() => { const endAt = now + 1; return buildLucidWeeklyReview(state!.experiments, { startAt: endAt - 7 * 86400000, endAt }); }, [now, state]);
  const dateKey = getLucidLocalDateKey(review.currentWindow.startAt);
  const practiceDays = new Set(state!.progress.flatMap((item) => item.practiceDates).filter((key) => key >= dateKey)).size;
  const close = () => closeLucidRoute(router, LUCID_HOME_HREF);
  const goBack = () => step === 0 ? close() : setStep((value) => value - 1);
  const save = async () => { setSaving(true); try { await saveWeeklyReview({ weekStart: dateKey, practiceDays: Math.min(7, practiceDays), recallDays: Math.min(7, review.current.recalledDreams), lucidDreams: review.current.lucidDreams, recommendedTechnique: review.coaching.technique, notes: notes.trim() || undefined }); Alert.alert(copy.saved, content.weeklyReview.coachingNote, [{ text: content.chrome.common.done, onPress: close }]); } finally { setSaving(false); } };
  const metrics = <View style={[styles.metrics, compact && styles.metricsCompact]}><LucidMetric value={String(practiceDays)} label={copy.practice} style={compact ? styles.metricCompact : undefined} /><LucidMetric value={String(review.current.recalledDreams)} label={copy.recall} style={compact ? styles.metricCompact : undefined} /><LucidMetric value={String(review.current.lucidDreams)} label={copy.lucid} style={compact ? styles.metricCompact : undefined} /></View>;
  const focus = review.coaching.technique ? content.programs[review.coaching.technique].title : copy[review.coaching.action];

  return <LucidScreen eyebrow={`${copy.step} ${step + 1} ${copy.of} 3`} title={step === 2 ? copy.summary : copy.title} subtitle={step === 0 ? content.weeklyReview.intro : undefined} trailing={<LucidIconAction label={step === 0 ? content.chrome.common.back : copy.back} icon={step === 0 ? 'close' : 'arrow-back'} onPress={goBack} />} testID="lucid-weekly">
    {step === 0 ? <View style={styles.step}><View style={styles.hero}><LucidIconTile icon="moon" tone="accent" size="lg" /><Text style={[styles.heroTitle, { color: palette.text }]}>{copy.summary}</Text></View>{metrics}<LucidCard accent="accent"><LucidPill label={copy.recommendation} tone="accent" icon="sparkles" /><Text style={[styles.recommendation, { color: palette.text }]}>{focus}</Text></LucidCard><LucidButton label={copy.continue} icon="arrow-forward" onPress={() => setStep(1)} testID="lucid-weekly-next" /></View> : null}
    {step === 1 ? <View style={styles.step}><View style={styles.hero}><LucidIconTile icon="leaf" tone="neutral" size="lg" /><Text style={[styles.heroTitle, { color: palette.text }]}>{copy.notes}</Text></View><TextInput accessibilityLabel={copy.notes} multiline maxLength={4000} onChangeText={setNotes} placeholder={copy.notes} placeholderTextColor={palette.textMuted} style={[styles.notes, { backgroundColor: palette.surface, borderColor: palette.borderInteractive, color: palette.text }]} testID="lucid-weekly-notes" textAlignVertical="top" value={notes} /><LucidButton label={copy.review} icon="arrow-forward" onPress={() => setStep(2)} testID="lucid-weekly-review" /></View> : null}
    {step === 2 ? <View style={styles.step}>{metrics}<LucidCard accent="accent"><LucidPill label={copy.recommendation} tone="accent" icon="sparkles" /><Text style={[styles.recommendation, { color: palette.text }]}>{focus}</Text><Text style={[styles.body, { color: palette.textSecondary }]}>{notes.trim() || copy.noNotes}</Text></LucidCard><LucidButton label={copy.save} icon="checkmark" loading={saving} onPress={() => void save()} testID="lucid-weekly-save" /></View> : null}
  </LucidScreen>;
}

const styles = StyleSheet.create({ step: { gap: LucidSpace.lg }, hero: { alignItems: 'center', gap: LucidSpace.md, paddingVertical: LucidSpace.lg }, heroTitle: { fontFamily: 'Fraunces_500Medium', fontSize: LucidType.h2[0], lineHeight: LucidType.h2[1], textAlign: 'center' }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: LucidSpace.sm }, metricsCompact: { flexDirection: 'column' }, metricCompact: { flexBasis: '100%' }, recommendation: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: LucidType.h3[0], lineHeight: LucidType.h3[1] }, body: { fontFamily: 'SpaceGrotesk_400Regular', fontSize: LucidType.caption[0], lineHeight: LucidType.caption[1] }, notes: { minHeight: 160, borderRadius: LucidRadius.lg, borderWidth: 1, padding: LucidSpace.lg, fontFamily: 'SpaceGrotesk_400Regular', fontSize: LucidType.bodySm[0], lineHeight: LucidType.bodySm[1], textAlignVertical: 'top' } });
