#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/assets/audio/sleep"
SAMPLE_RATE=48000
DURATION=2700
FADE_DURATION=30
FADE_START=$((DURATION - FADE_DURATION))
AAC_BITRATE=40k

for tool in ffmpeg ffprobe; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Missing required tool: $tool" >&2
    exit 1
  fi
done

mkdir -p "$OUTPUT_DIR"

generate_rain() {
  ffmpeg -hide_banner -loglevel error -y \
    -f lavfi -i "anoisesrc=color=pink:amplitude=0.58:seed=1101:sample_rate=${SAMPLE_RATE}:duration=${DURATION}" \
    -f lavfi -i "anoisesrc=color=white:amplitude=0.30:seed=1103:sample_rate=${SAMPLE_RATE}:duration=${DURATION}" \
    -filter_complex \
      "[0:a]highpass=f=500,lowpass=f=11500,volume=0.48[body];\
       [1:a]highpass=f=3800,lowpass=f=15000,volume=0.12[drops];\
       [body][drops]amix=inputs=2:normalize=0,afade=t=out:st=${FADE_START}:d=${FADE_DURATION}[out]" \
    -map "[out]" \
    -ar "$SAMPLE_RATE" \
    -ac 1 \
    -c:a aac \
    -b:a "$AAC_BITRATE" \
    -movflags +faststart \
    -metadata title="Gentle Rain" \
    -metadata artist="Noctalia" \
    -metadata comment="Original procedural sound generated by scripts/generate-sleep-sounds.sh" \
    "$OUTPUT_DIR/rain.m4a"
}

generate_ocean_waves() {
  ffmpeg -hide_banner -loglevel error -y \
    -f lavfi -i "anoisesrc=color=brown:amplitude=0.72:seed=2201:sample_rate=${SAMPLE_RATE}:duration=${DURATION}" \
    -f lavfi -i "anoisesrc=color=pink:amplitude=0.38:seed=2203:sample_rate=${SAMPLE_RATE}:duration=${DURATION}" \
    -filter_complex \
      "[0:a]highpass=f=45,lowpass=f=1300,volume='0.33+0.12*sin(2*PI*t/18)+0.05*sin(2*PI*t/10)':eval=frame[swell];\
       [1:a]highpass=f=700,lowpass=f=4200,volume='0.075+0.035*sin(2*PI*t/18-0.50)':eval=frame[foam];\
       [swell][foam]amix=inputs=2:normalize=0,afade=t=out:st=${FADE_START}:d=${FADE_DURATION}[out]" \
    -map "[out]" \
    -ar "$SAMPLE_RATE" \
    -ac 1 \
    -c:a aac \
    -b:a "$AAC_BITRATE" \
    -movflags +faststart \
    -metadata title="Ocean Waves" \
    -metadata artist="Noctalia" \
    -metadata comment="Original procedural sound generated by scripts/generate-sleep-sounds.sh" \
    "$OUTPUT_DIR/ocean-waves.m4a"
}

generate_brown_noise() {
  ffmpeg -hide_banner -loglevel error -y \
    -f lavfi -i "anoisesrc=color=brown:amplitude=0.76:seed=3301:sample_rate=${SAMPLE_RATE}:duration=${DURATION}" \
    -filter_complex \
      "[0:a]highpass=f=35,lowpass=f=5200,volume=0.46,afade=t=out:st=${FADE_START}:d=${FADE_DURATION}[out]" \
    -map "[out]" \
    -ar "$SAMPLE_RATE" \
    -ac 1 \
    -c:a aac \
    -b:a "$AAC_BITRATE" \
    -movflags +faststart \
    -metadata title="Brown Noise" \
    -metadata artist="Noctalia" \
    -metadata comment="Original procedural sound generated by scripts/generate-sleep-sounds.sh" \
    "$OUTPUT_DIR/brown-noise.m4a"
}

validate_output() {
  local output_file="$1"
  local codec duration channels size

  codec="$(ffprobe -v error -select_streams a:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$output_file")"
  duration="$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$output_file")"
  channels="$(ffprobe -v error -select_streams a:0 -show_entries stream=channels -of default=noprint_wrappers=1:nokey=1 "$output_file")"
  size="$(ffprobe -v error -show_entries format=size -of default=noprint_wrappers=1:nokey=1 "$output_file")"

  if [[ "$codec" != "aac" || "$channels" != "1" ]]; then
    echo "Invalid audio stream in $output_file (codec=$codec, channels=$channels)" >&2
    exit 1
  fi

  if ! awk -v duration="$duration" 'BEGIN { exit !(duration >= 2699.9 && duration <= 2700.1) }'; then
    echo "Unexpected duration in $output_file: $duration seconds" >&2
    exit 1
  fi

  if (( size > 16000000 )); then
    echo "Audio asset is larger than expected: $output_file ($size bytes)" >&2
    exit 1
  fi

  printf '%s: codec=%s duration=%.3fs channels=%s size=%s bytes\n' \
    "$(basename "$output_file")" "$codec" "$duration" "$channels" "$size"
}

generate_rain
generate_ocean_waves
generate_brown_noise

validate_output "$OUTPUT_DIR/rain.m4a"
validate_output "$OUTPUT_DIR/ocean-waves.m4a"
validate_output "$OUTPUT_DIR/brown-noise.m4a"
