import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';

import { LucidButton, LucidCard, LucidMetric, LucidPill, LucidScreen, LucidSectionHeader } from '@/components/lucid/LucidUI';
import { getLucidPalette } from '@/constants/lucidTheme';
import { useLucidTrainer } from '@/context/LucidTrainerContext';
import { useTheme } from '@/context/ThemeContext';
import { useLucidNow } from '@/hooks/useLucidNow';
import { buildLucidWeeklyReview } from '@/lib/lucid/progress';

const COPY = {
  en: { eyebrow: 'Progress', title: 'Patterns, not promises', subtitle: 'Compare your own observations. Small samples are shown as early signals, never conclusions.', overview: 'Last 7 days', attempts: 'attempts', recall: 'recall rate', lucid: 'lucid dreams', sleep: 'sleep quality', methods: 'Method comparison', attemptsShort: 'attempts', noData: 'No attempts yet', early: 'Early signal', usable: 'Personal signal', history: 'Recent experiences', empty: 'Your morning reviews will appear here.', weekly: 'Complete weekly review', weeklyHistory: 'Saved weekly reviews', weeklyEmpty: 'Saved weekly reviews will appear here after you complete one.', weeklyPractice: 'practice days', weeklyRecall: 'recall days', weeklyFocus: 'Suggested focus', delete: 'Delete this review?', cancel: 'Cancel', confirm: 'Delete', none: 'No lucidity', pre_lucid: 'Almost lucid', resultLucid: 'Lucid', coach: 'Offline adaptation', improving: 'Trend improving', steady: 'Trend steady', declining: 'Trend declining', insufficient_data: 'More observations needed' },
  fr: { eyebrow: 'Progression', title: 'Des tendances, pas des promesses', subtitle: 'Comparez vos propres observations. Les petits échantillons restent des signaux précoces, jamais des conclusions.', overview: '7 derniers jours', attempts: 'essais', recall: 'taux de rappel', lucid: 'rêves lucides', sleep: 'qualité du sommeil', methods: 'Comparaison des méthodes', attemptsShort: 'essais', noData: 'Aucun essai', early: 'Signal précoce', usable: 'Signal personnel', history: 'Expériences récentes', empty: 'Vos bilans du matin apparaîtront ici.', weekly: 'Faire le bilan hebdomadaire', weeklyHistory: 'Bilans hebdomadaires enregistrés', weeklyEmpty: 'Les bilans hebdomadaires enregistrés apparaîtront ici après le premier.', weeklyPractice: 'jours de pratique', weeklyRecall: 'jours de rappel', weeklyFocus: 'Axe suggéré', delete: 'Supprimer ce bilan ?', cancel: 'Annuler', confirm: 'Supprimer', none: 'Pas de lucidité', pre_lucid: 'Presque lucide', resultLucid: 'Lucide', coach: 'Adaptation hors ligne', improving: 'Tendance en progrès', steady: 'Tendance stable', declining: 'Tendance en baisse', insufficient_data: 'Plus d’observations nécessaires' },
  es: { eyebrow: 'Progreso', title: 'Patrones, no promesas', subtitle: 'Compara tus propias observaciones. Las muestras pequeñas son señales tempranas, no conclusiones.', overview: 'Últimos 7 días', attempts: 'intentos', recall: 'tasa de recuerdo', lucid: 'sueños lúcidos', sleep: 'calidad del sueño', methods: 'Comparación de métodos', attemptsShort: 'intentos', noData: 'Sin intentos', early: 'Señal temprana', usable: 'Señal personal', history: 'Experiencias recientes', empty: 'Tus revisiones matinales aparecerán aquí.', weekly: 'Completar revisión semanal', weeklyHistory: 'Revisiones semanales guardadas', weeklyEmpty: 'Las revisiones semanales guardadas aparecerán aquí después de completar una.', weeklyPractice: 'días de práctica', weeklyRecall: 'días de recuerdo', weeklyFocus: 'Foco sugerido', delete: '¿Eliminar esta revisión?', cancel: 'Cancelar', confirm: 'Eliminar', none: 'Sin lucidez', pre_lucid: 'Casi lúcido', resultLucid: 'Lúcido', coach: 'Adaptación sin conexión', improving: 'Tendencia al alza', steady: 'Tendencia estable', declining: 'Tendencia a la baja', insufficient_data: 'Se necesitan más observaciones' },
  de: { eyebrow: 'Fortschritt', title: 'Muster statt Versprechen', subtitle: 'Vergleiche deine Beobachtungen. Kleine Stichproben sind frühe Signale, keine Schlüsse.', overview: 'Letzte 7 Tage', attempts: 'Versuche', recall: 'Erinnerungsrate', lucid: 'Klarträume', sleep: 'Schlafqualität', methods: 'Methodenvergleich', attemptsShort: 'Versuche', noData: 'Keine Versuche', early: 'Frühes Signal', usable: 'Persönliches Signal', history: 'Letzte Erfahrungen', empty: 'Deine Morgenrückblicke erscheinen hier.', weekly: 'Wochenrückblick', weeklyHistory: 'Gespeicherte Wochenrückblicke', weeklyEmpty: 'Gespeicherte Wochenrückblicke erscheinen hier nach dem ersten Abschluss.', weeklyPractice: 'Übungstage', weeklyRecall: 'Erinnerungstage', weeklyFocus: 'Vorgeschlagener Fokus', delete: 'Diesen Rückblick löschen?', cancel: 'Abbrechen', confirm: 'Löschen', none: 'Keine Klarheit', pre_lucid: 'Fast klar', resultLucid: 'Klar', coach: 'Offline-Anpassung', improving: 'Trend verbessert sich', steady: 'Trend stabil', declining: 'Trend sinkt', insufficient_data: 'Mehr Beobachtungen nötig' },
  it: { eyebrow: 'Progressi', title: 'Schemi, non promesse', subtitle: 'Confronta le tue osservazioni. I piccoli campioni sono segnali iniziali, non conclusioni.', overview: 'Ultimi 7 giorni', attempts: 'tentativi', recall: 'tasso di ricordo', lucid: 'sogni lucidi', sleep: 'qualità del sonno', methods: 'Confronto metodi', attemptsShort: 'tentativi', noData: 'Nessun tentativo', early: 'Segnale iniziale', usable: 'Segnale personale', history: 'Esperienze recenti', empty: 'I bilanci mattutini appariranno qui.', weekly: 'Completa bilancio settimanale', weeklyHistory: 'Bilanci settimanali salvati', weeklyEmpty: 'I bilanci settimanali salvati appariranno qui dopo il primo.', weeklyPractice: 'giorni di pratica', weeklyRecall: 'giorni di ricordo', weeklyFocus: 'Focus suggerito', delete: 'Eliminare questo bilancio?', cancel: 'Annulla', confirm: 'Elimina', none: 'Nessuna lucidità', pre_lucid: 'Quasi lucido', resultLucid: 'Lucido', coach: 'Adattamento offline', improving: 'Tendenza in crescita', steady: 'Tendenza stabile', declining: 'Tendenza in calo', insufficient_data: 'Servono più osservazioni' },
} as const;

export default function LucidProgressScreen() {
  const { colors, mode } = useTheme(); const palette = getLucidPalette(colors, mode);
  const { state, content, deleteExperiment } = useLucidTrainer(); const copy = COPY[content.locale];
  const now = useLucidNow();
  const review = useMemo(() => { const endAt = now + 1; return buildLucidWeeklyReview(state!.experiments, { startAt: endAt - 7 * 86400000, endAt }); }, [now, state]);
  const weeklyReviews = useMemo(
    () => [...state!.weeklyReviews].sort((a, b) => b.weekStart.localeCompare(a.weekStart) || a.id.localeCompare(b.id)).slice(0, 12),
    [state]
  );
  const avgSleep = review.current.averageSleepQuality;
  const maxAttempts = Math.max(1, ...review.comparison.methods.map((method) => method.attempts));
  const confirmDelete = (id: string) => Alert.alert(copy.delete, undefined, [{ text: copy.cancel, style: 'cancel' }, { text: copy.confirm, style: 'destructive', onPress: () => void deleteExperiment(id) }]);
  return (
    <LucidScreen testID="lucid-progress" eyebrow={copy.eyebrow} title={copy.title} subtitle={copy.subtitle}>
      <LucidSectionHeader title={copy.overview} action={<LucidPill label={copy[review.trend.direction]} tone={review.trend.direction === 'improving' ? 'cyan' : review.trend.direction === 'declining' ? 'amber' : 'neutral'} />} />
      <View style={styles.metrics}><LucidMetric value={String(review.current.attempts)} label={copy.attempts} /><LucidMetric value={review.current.recallRate == null ? '—' : `${Math.round(review.current.recallRate * 100)}%`} label={copy.recall} tone="cyan" /><LucidMetric value={String(review.current.lucidDreams)} label={copy.lucid} tone="amber" /><LucidMetric value={avgSleep == null ? '—' : avgSleep.toFixed(1)} label={`${copy.sleep} / 5`} tone="cyan" /></View>
      <LucidCard accent="cyan"><View style={styles.coachTop}><LucidPill label={copy.coach} tone="cyan" icon="sparkles" /><Ionicons name="phone-portrait" size={18} color={palette.textMuted} /></View><Text style={[styles.coachText, { color: palette.text }]}>{content.weeklyReview.adaptationRules[review.coaching.action === 'protect_sleep' ? 0 : review.coaching.action === 'strengthen_recall' ? 1 : 2] ?? content.weeklyReview.coachingNote}</Text><Text style={[styles.small, { color: palette.textSecondary }]}>{content.weeklyReview.coachingNote}</Text></LucidCard>
      <LucidSectionHeader title={copy.methods} />
      <LucidCard>
        {review.comparison.methods.map((method) => { const rate = method.successRate ?? 0; const leader = review.comparison.leader === method.technique; return <View key={method.technique} style={styles.method}><View style={styles.methodTop}><Text style={[styles.methodName, { color: palette.text }]}>{content.programs[method.technique].title}</Text><Text style={[styles.methodMeta, { color: palette.textSecondary }]}>{method.attempts ? `${method.attempts} ${copy.attemptsShort} · ${Math.round(rate * 100)}%` : copy.noData}</Text></View><View style={[styles.bar, { backgroundColor: palette.surfaceRaised }]}><View style={[styles.barFill, { width: `${method.attempts ? Math.max(8, (method.attempts / maxAttempts) * 100) : 0}%`, backgroundColor: leader ? palette.cyan : palette.accent }]} /></View></View>; })}
        <Text style={[styles.small, { color: palette.textMuted }]}>{review.comparison.evidence === 'usable' ? copy.usable : copy.early}</Text>
      </LucidCard>
      <LucidButton label={copy.weekly} variant="secondary" icon="calendar" onPress={() => router.push('/lucid/weekly')} />
      <LucidSectionHeader title={copy.weeklyHistory} />
      {weeklyReviews.length === 0 ? <LucidCard testID="lucid-weekly-history-empty"><Text style={[styles.empty, { color: palette.textSecondary }]}>{copy.weeklyEmpty}</Text></LucidCard> : weeklyReviews.map((item) => {
        const weekLabel = new Intl.DateTimeFormat(content.locale, { dateStyle: 'medium' }).format(new Date(`${item.weekStart}T00:00:00`));
        const practiceLabel = `${copy.weeklyPractice}: ${item.practiceDays}`;
        const recallLabel = `${copy.weeklyRecall}: ${item.recallDays}`;
        const lucidLabel = `${copy.lucid}: ${item.lucidDreams}`;
        const focusLabel = item.recommendedTechnique ? `${copy.weeklyFocus}: ${content.programs[item.recommendedTechnique].title}` : null;
        return <LucidCard accessibilityLabel={[weekLabel, focusLabel, practiceLabel, recallLabel, lucidLabel].filter(Boolean).join('. ')} key={item.id} testID={`lucid-weekly-history-${item.id}`}><View style={styles.historyTop}><View style={styles.historyCopy}><Text style={[styles.methodName, { color: palette.text }]}>{weekLabel}</Text>{focusLabel ? <Text style={[styles.methodMeta, { color: palette.textSecondary }]}>{focusLabel}</Text> : null}</View></View><View style={styles.historyScores}><LucidPill label={practiceLabel} tone="cyan" /><LucidPill label={recallLabel} tone="neutral" /><LucidPill label={lucidLabel} tone="amber" /></View>{item.notes ? <Text numberOfLines={2} style={[styles.small, { color: palette.textSecondary }]}>{item.notes}</Text> : null}</LucidCard>;
      })}
      <LucidSectionHeader title={copy.history} />
      {state!.experiments.length === 0 ? <LucidCard><Text style={[styles.empty, { color: palette.textSecondary }]}>{copy.empty}</Text><LucidButton label={content.morningReview.title} icon="sunny" onPress={() => router.push('/lucid/morning')} /></LucidCard> : state!.experiments.slice(0, 12).map((item) => <LucidCard key={item.id}><View style={styles.historyTop}><View style={styles.historyCopy}><Text style={[styles.methodName, { color: palette.text }]}>{content.programs[item.technique].title}</Text><Text style={[styles.methodMeta, { color: palette.textSecondary }]}>{new Intl.DateTimeFormat(content.locale, { dateStyle: 'medium' }).format(item.occurredAt)} · {item.result === 'lucid' ? copy.resultLucid : copy[item.result]}</Text></View><Ionicons accessibilityLabel={copy.confirm} name="trash-outline" size={19} color={palette.danger} onPress={() => confirmDelete(item.id)} /></View><View style={styles.historyScores}><LucidPill label={`${copy.recall}: ${item.recallLevel}/5`} tone="cyan" /><LucidPill label={`${copy.sleep}: ${item.sleepQuality}/5`} tone="neutral" /></View>{item.notes ? <Text numberOfLines={2} style={[styles.small, { color: palette.textSecondary }]}>{item.notes}</Text> : null}</LucidCard>)}
    </LucidScreen>
  );
}

const styles = StyleSheet.create({ metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, coachTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, coachText: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: 15, lineHeight: 22 }, small: { fontFamily: 'SpaceGrotesk_400Regular', fontSize: 12, lineHeight: 17 }, method: { gap: 7 }, methodTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, methodName: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: 14 }, methodMeta: { fontFamily: 'SpaceGrotesk_400Regular', fontSize: 11 }, bar: { height: 8, borderRadius: 4, overflow: 'hidden' }, barFill: { height: '100%', borderRadius: 4 }, empty: { fontFamily: 'SpaceGrotesk_400Regular', fontSize: 14, lineHeight: 21, textAlign: 'center' }, historyTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, historyCopy: { flex: 1, gap: 4 }, historyScores: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 } });
