import type { LucidTrainerContent } from './types';

const content = {
  locale: 'en',
  chrome: {
    appName: 'Noctalia Lucid Trainer',
    tagline: 'Train awareness while protecting your sleep.',
    tabs: {
      today: 'Today',
      programs: 'Programs',
      night: 'Night',
      progress: 'Progress',
      settings: 'Settings',
    },
    common: {
      continue: 'Continue',
      back: 'Back',
      save: 'Save',
      cancel: 'Cancel',
      done: 'Done',
      retry: 'Try again',
      skipTonight: 'Skip tonight',
      optional: 'Optional',
      offlineReady: 'Available offline',
      loading: 'Loading your training…',
      error: 'This could not be loaded. Your saved training remains on this device.',
    },
  },
  onboarding: {
    title: 'Build a lucid-dream practice that fits your sleep',
    intro: 'Lucid Trainer develops daytime awareness, bedtime preparation and morning reflection. A lucid dream may or may not occur; the practice is the goal.',
    wellbeingNotice: 'This is a wellbeing and self-observation tool, not medical care. Protect sleep first and stop any exercise that leaves you distressed or unusually tired.',
    goalTitle: 'What would you like to practice?',
    goals: [
      { id: 'first_lucid_dream', title: 'Notice more', description: 'Build deliberate attention and recognize unusual details while working toward a first lucid experience.' },
      { id: 'improve_recall', title: 'Remember dreams', description: 'Strengthen the morning habit before adding night techniques.' },
      { id: 'more_frequent_lucidity', title: 'Explore lucidity more often', description: 'Practice evidence-informed methods without expecting a fixed outcome.' },
      { id: 'stabilize_lucidity', title: 'Stay lucid with less effort', description: 'Practice a calm response after recognizing a dream, without promising longer experiences.' },
    ],
    experienceTitle: 'What is your experience?',
    experienceLevels: [
      { id: 'beginner', title: 'New', description: 'I have not followed a structured lucid-dream practice.' },
      { id: 'occasional', title: 'Occasional', description: 'I have tried a few exercises or had isolated lucid dreams.' },
      { id: 'experienced', title: 'Regular', description: 'I already track dreams and want a more consistent routine.' },
    ],
    reminderTitle: 'Choose a realistic rhythm',
    reminderExplanation: 'Start with a few meaningful reminders. More alerts do not make a reality check more attentive.',
    sleepScheduleTitle: 'Set your usual sleep window',
    sleepScheduleExplanation: 'Your bedtime and wake time keep preparation and optional night cues inside the window you choose. You can change or pause them at any time.',
    permissionsTitle: 'Permissions, only when useful',
    notificationPermission: 'Notifications are requested only after you create a reminder. If you decline, the training remains usable and shows manual prompts.',
    audioPermission: 'Night audio is off by default. Preview it while awake, set a quiet volume and timer, then choose whether to enable it. The microphone is not needed.',
    accessibilityTitle: 'Adapt the experience',
    accessibilityBody: 'System text size, screen readers, reduced motion and light or dark appearance are supported. Essential steps never rely on color or animation alone.',
    consentTitle: 'Your choices stay yours',
    consentItems: [
      'Training works offline without an account.',
      'Product analytics are minimal and optional.',
      'Connecting Noctalia and transferring a short morning summary are separate, revocable choices.',
      'You can export or delete your training data from settings.',
    ],
    finishAction: 'Create my training plan',
  },
  programs: {
    mild: {
      id: 'mild',
      title: 'MILD',
      expandedName: 'Mnemonic Induction of Lucid Dreams',
      summary: 'Rehearse a clear intention to recognize a future dream, using a remembered scene and a personal dream sign.',
      evidenceNote: 'MILD is among the better-studied cognitive methods, but study quality and individual results vary.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023', 'stumbrys-2012'],
      prerequisites: [
        'Keep a stable sleep opportunity.',
        'Have a recent dream or imagined scene available for rehearsal.',
        'Be willing to record a brief result in the morning, including no recall.',
      ],
      stopRules: [
        'Pause night practice after poor sleep or marked daytime tiredness.',
        'Return to bedtime-only practice if an awakening makes it hard to fall asleep again.',
        'Stop and seek appropriate support if the exercises cause distress or blur waking and dream experiences.',
      ],
      sessions: [
        {
          id: 'mild-01', session: 1, title: 'Set a precise intention',
          objective: 'Understand MILD and choose one short, believable intention.', durationMinutes: 10,
          steps: ['Read the method summary once.', 'Write: “When I am dreaming, I intend to notice it.”', 'Say the intention slowly three times, focusing on remembering rather than forcing an outcome.'],
          caution: 'Practice while awake today; do not shorten your sleep to complete this session.',
          reflectionPrompt: 'Which words made the intention feel clear and calm?',
        },
        {
          id: 'mild-02', session: 2, title: 'Find a dream sign',
          objective: 'Identify one recurring or unusual detail that can cue awareness.', durationMinutes: 12,
          steps: ['Review one recent dream or use a neutral imagined scene.', 'Circle one odd place, event, person or sensation.', 'Picture noticing that sign and pausing to ask whether you are dreaming.'],
          caution: 'Choose a neutral scene if recalling a dream feels unpleasant.',
          reflectionPrompt: 'What sign would be easiest to recognize without strain?',
        },
        {
          id: 'mild-03', session: 3, title: 'Train prospective memory',
          objective: 'Practice remembering an intention when a future cue appears.', durationMinutes: 8,
          steps: ['Choose three ordinary cues for today, such as opening a door.', 'When each cue appears, pause and recall your lucid intention before checking the app.', 'Mark the cue as noticed; missed cues are useful observations, not failures.'],
          caution: 'Use cues only in safe moments, never while driving or handling equipment.',
          reflectionPrompt: 'Which context helped you remember without a notification?',
        },
        {
          id: 'mild-04', session: 4, title: 'Rehearse the recognition moment',
          objective: 'Link intention, dream sign and a calm response.', durationMinutes: 12,
          steps: ['Recall your chosen scene from the beginning.', 'At the dream sign, imagine noticing: “This is a dream.”', 'Imagine looking around calmly, then repeat the intention once.'],
          caution: 'Keep the rehearsal brief and stop if imagery becomes activating near bedtime.',
          reflectionPrompt: 'What calm action would help you stay oriented in the imagined scene?',
        },
        {
          id: 'mild-05', session: 5, title: 'Use MILD at bedtime',
          objective: 'Complete a low-disruption MILD sequence before normal sleep.', durationMinutes: 10,
          steps: ['Prepare your morning check-in before getting into bed.', 'Recall the scene, notice the sign and repeat your intention.', 'Release the exercise and let sleep arrive normally.'],
          caution: 'If repetition keeps you alert, stop the exercise and return to your usual wind-down.',
          reflectionPrompt: 'Did the sequence feel settling, neutral or alerting?',
        },
        {
          id: 'mild-06', session: 6, title: 'Optional natural-awakening practice',
          objective: 'Try MILD after a spontaneous awakening without scheduling sleep loss.', durationMinutes: 6,
          steps: ['Use only a natural awakening with enough sleep time remaining.', 'Recall the dream fragment you just had, or reuse your practiced scene.', 'Set the intention once or twice, then prioritize returning to sleep.'],
          caution: 'Skip this session after insufficient sleep or if awakenings usually keep you awake.',
          reflectionPrompt: 'How quickly did you settle after ending the exercise?',
        },
        {
          id: 'mild-07', session: 7, title: 'Review and adapt',
          objective: 'Choose a sustainable MILD rhythm from your observations.', durationMinutes: 15,
          steps: ['Compare recall, sleep quality and lucidity notes across the week.', 'Keep the shortest version that did not disturb sleep.', 'Plan two or three practice nights, leaving recovery nights between demanding attempts.'],
          caution: 'Do not increase frequency to compensate for a week without lucidity.',
          reflectionPrompt: 'Which part is worth keeping even when no lucid dream occurs?',
        },
      ],
    },
    ssild: {
      id: 'ssild',
      title: 'SSILD',
      expandedName: 'Senses Initiated Lucid Dream',
      summary: 'Move relaxed attention through sight, hearing and body sensations, without trying to create an experience.',
      evidenceNote: 'SSILD has promising field-study results, but fewer independent replications than MILD.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023'],
      prerequisites: [
        'Be comfortable observing sensations without judging them.',
        'Know how to stop and return to normal rest if attention becomes effortful.',
        'Keep all essential instructions available offline before bedtime.',
      ],
      stopRules: [
        'Stop cycles when they increase alertness or discomfort.',
        'Skip post-awakening practice when sleep time is limited.',
        'Choose a daytime grounding exercise instead if internal sensations feel unsettling.',
      ],
      sessions: [
        {
          id: 'ssild-01', session: 1, title: 'Observe without producing',
          objective: 'Learn passive attention to one sense at a time.', durationMinutes: 9,
          steps: ['Sit comfortably during the day.', 'Notice visual darkness or ambient light for one minute.', 'Notice sound, then contact and temperature, allowing each experience to be ordinary.'],
          caution: 'Keep eyes open if closing them feels uncomfortable or disorienting.',
          reflectionPrompt: 'Which sense was easiest to observe without effort?',
        },
        {
          id: 'ssild-02', session: 2, title: 'Learn quick cycles',
          objective: 'Move lightly through sight, sound and body.', durationMinutes: 8,
          steps: ['Give sight a few relaxed seconds.', 'Shift to sounds for a few seconds.', 'Shift to body sensations, then repeat four cycles without counting precisely.'],
          caution: 'Do not hold your breath, strain your eyes or search for unusual sensations.',
          reflectionPrompt: 'Could you shift attention without checking whether anything special happened?',
        },
        {
          id: 'ssild-03', session: 3, title: 'Learn slow cycles',
          objective: 'Sustain gentle attention across the three senses.', durationMinutes: 12,
          steps: ['Rest attention on sight for roughly twenty seconds.', 'Move to hearing, then body sensations for similar unforced periods.', 'Complete four slow cycles and end before concentration becomes work.'],
          caution: 'Approximate the timing; clock-watching can make the exercise more alerting.',
          reflectionPrompt: 'At what point did relaxed observation become effort?',
        },
        {
          id: 'ssild-04', session: 4, title: 'Build the full sequence',
          objective: 'Combine quick and slow cycles into one familiar routine.', durationMinutes: 14,
          steps: ['Complete four quick cycles.', 'Complete four slow cycles.', 'Finish with a normal breath and let attention broaden to the whole body.'],
          caution: 'This is rehearsal while awake; keep your normal sleep schedule unchanged.',
          reflectionPrompt: 'What simple cue will remind you to stay passive?',
        },
        {
          id: 'ssild-05', session: 5, title: 'Try a bedtime version',
          objective: 'Use a shortened sequence without delaying sleep.', durationMinutes: 8,
          steps: ['Settle into your usual sleeping position.', 'Complete two quick and two slow cycles.', 'Stop deliberately and allow sleep, even if the sequence feels incomplete.'],
          caution: 'If the sequence delays sleep, remove it from bedtime and keep daytime practice only.',
          reflectionPrompt: 'Did the shortened version protect your wind-down?',
        },
        {
          id: 'ssild-06', session: 6, title: 'Optional awakening sequence',
          objective: 'Try the full sequence after a natural awakening when conditions are suitable.', durationMinutes: 10,
          steps: ['Confirm that enough sleep time remains and you feel calm.', 'Complete four quick cycles followed by four to six slow cycles.', 'End the exercise and return to sleep without evaluating it.'],
          caution: 'Skip after poor sleep, during illness, or when you need maximum alertness the next day.',
          reflectionPrompt: 'Were you able to return to sleep comfortably?',
        },
        {
          id: 'ssild-07', session: 7, title: 'Choose your sustainable dose',
          objective: 'Adapt SSILD from sleep and experience notes, not outcome pressure.', durationMinutes: 15,
          steps: ['Review completion, sleep quality, recall and lucidity.', 'Choose daytime, bedtime or occasional awakening practice.', 'Schedule recovery nights and keep the least disruptive effective-feeling version.'],
          caution: 'A neutral week is a valid result; do not add cycles or awakenings automatically.',
          reflectionPrompt: 'Which version felt calm enough to repeat?',
        },
      ],
    },
    wbtb: {
      id: 'wbtb',
      title: 'WBTB',
      expandedName: 'Wake Back To Bed',
      summary: 'Use a planned or natural late-night awakening, a short calm interval and a return to sleep with a chosen cognitive technique.',
      evidenceNote: 'WBTB is commonly paired with MILD or SSILD. Because it interrupts sleep, it should remain occasional and subordinate to sleep needs.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023', 'aasm-srs-2015'],
      prerequisites: [
        'Reserve enough time for your normal sleep opportunity plus the brief awakening.',
        'Choose a morning without safety-critical early duties.',
        'Know which quiet technique you will use before setting any alarm.',
      ],
      stopRules: [
        'Cancel the attempt after sleep loss, illness, unusual fatigue or repeated awakenings.',
        'End the wake interval early if you become too alert.',
        'Pause WBTB if sleep quality or daytime functioning worsens.',
      ],
      sessions: [
        {
          id: 'wbtb-01', session: 1, title: 'Check readiness',
          objective: 'Decide when WBTB should be skipped before planning an alarm.', durationMinutes: 10,
          steps: ['Review your recent sleep opportunity and daytime alertness.', 'List next-morning obligations and safety needs.', 'Write one clear cancellation rule for tonight.'],
          caution: 'This session contains no night awakening; do not attempt WBTB when already short on sleep.',
          reflectionPrompt: 'What signal will make skipping the responsible choice?',
        },
        {
          id: 'wbtb-02', session: 2, title: 'Design a quiet awakening',
          objective: 'Prepare an optional alarm that minimizes disruption.', durationMinutes: 10,
          steps: ['Choose an occasional night with enough time in bed.', 'Select a gentle alarm and a simple way to stop it.', 'Prepare dim lighting and offline instructions before bed.'],
          caution: 'Do not use headphones while sleeping or a volume that may startle you or others.',
          reflectionPrompt: 'Can the setup be cancelled without losing any training progress?',
        },
        {
          id: 'wbtb-03', session: 3, title: 'Rehearse the wake interval by day',
          objective: 'Learn a short, low-stimulation sequence before using it at night.', durationMinutes: 12,
          steps: ['Practice getting up slowly and using dim light.', 'Read one short technique card without opening other apps.', 'Return to bed and complete two minutes of calm breathing.'],
          caution: 'This daytime rehearsal replaces a night attempt today.',
          reflectionPrompt: 'Which part could create unnecessary stimulation at night?',
        },
        {
          id: 'wbtb-04', session: 4, title: 'Choose the paired technique',
          objective: 'Pair WBTB with one familiar method rather than improvising.', durationMinutes: 10,
          steps: ['Choose the MILD intention or the SSILD sequence already practiced.', 'Place only that instruction beside the bed.', 'Set a maximum wake interval and a stop point.'],
          caution: 'Do not combine multiple methods or extend wakefulness to chase an outcome.',
          reflectionPrompt: 'Which single technique is easiest to perform quietly?',
        },
        {
          id: 'wbtb-05', session: 5, title: 'Optional first night',
          objective: 'Run one conservative WBTB attempt with sleep protection.', durationMinutes: 15,
          steps: ['On waking, reassess tiredness and cancel if conditions changed.', 'Stay in dim light for only the planned short interval.', 'Complete the chosen technique, return to bed and release the goal.'],
          caution: 'Stop immediately if you feel unwell or too awake; prioritize returning to rest.',
          reflectionPrompt: 'How disruptive was the full sequence, regardless of dream outcome?',
        },
        {
          id: 'wbtb-06', session: 6, title: 'Protect the following day',
          objective: 'Use daytime functioning as a safety signal for future attempts.', durationMinutes: 8,
          steps: ['Rate sleep quality and alertness honestly.', 'Avoid another WBTB attempt tonight.', 'If drowsy, avoid driving or hazardous tasks and follow your usual safety plan.'],
          caution: 'Training data never takes priority over immediate safety or needed rest.',
          reflectionPrompt: 'Did the attempt affect concentration, mood or energy?',
        },
        {
          id: 'wbtb-07', session: 7, title: 'Set an occasional rhythm',
          objective: 'Decide whether WBTB belongs in your plan at all.', durationMinutes: 15,
          steps: ['Compare sleep, return-to-sleep time, recall and lucidity notes.', 'Keep WBTB only if disruption stayed low.', 'Choose a conservative maximum frequency with recovery nights, or disable it.'],
          caution: 'Do not schedule WBTB as a daily requirement; disabling it is a complete plan.',
          reflectionPrompt: 'Does the possible benefit justify the sleep interruption for you?',
        },
      ],
    },
  },
  realityChecks: {
    title: 'Reality checks with attention',
    intro: 'A useful check is a brief interruption of autopilot: notice context, test one stable detail and imagine recognizing the same mismatch in a dream.',
    qualityPrinciples: ['Pause before acting.', 'Ask the question with genuine uncertainty.', 'Use two pieces of evidence, not habit alone.', 'End with a calm intention for the next dream.'],
    exercises: [
      { id: 'text', title: 'Read twice', description: 'Read a short line, look away, then read it again and notice whether it stays stable.' },
      { id: 'time', title: 'Check time twice', description: 'Look at the time, look away, then compare it without rushing.' },
      { id: 'hands', title: 'Inspect your hands', description: 'Count fingers and notice shape, texture and continuity without trying to force an anomaly.' },
      { id: 'context', title: 'Trace the context', description: 'Ask how you arrived here and name the last two events you remember.' },
    ],
    contextTitle: 'Attach checks to meaningful contexts',
    contextExamples: ['After noticing something surprising', 'When entering a familiar room', 'After a strong emotion settles', 'When a recurring personal dream sign appears while awake'],
    reminderSafety: 'Dismiss reminders when attention is needed elsewhere. Never perform a check while driving, crossing a road or operating equipment.',
    completionPrompt: 'What evidence did you actually inspect?',
  },
  nightSignals: {
    title: 'Optional night audio cues',
    intro: 'A cue is a quiet prompt, not a command. Its timing cannot know your sleep stage unless supported by separately validated sensing, so use conservative timers and judge it by sleep impact.',
    optionalLabel: 'Off by default',
    setupSteps: ['Preview the exact sound while fully awake.', 'Start at the lowest clearly audible volume.', 'Choose a short timer and automatic stop.', 'Confirm that tomorrow allows normal recovery sleep.'],
    safeguards: ['Do not sleep with headphones or earbuds.', 'Do not use cues when they disturb a partner, child or animal.', 'Skip cues after poor sleep, illness or unusual fatigue.', 'Stop using a cue if it repeatedly wakes or startles you.'],
    previewAction: 'Preview while awake',
    timerLabel: 'Automatic stop timer',
    volumeLabel: 'Gentle cue volume',
    stopAction: 'Stop all night cues',
  },
  morningReview: {
    title: 'Morning check-in',
    intro: 'Record what happened before interpretation. A blank or non-lucid night is useful training data.',
    fields: {
      technique: 'Technique used', preparation: 'Preparation completed', dreamRecall: 'Dream recall', lucidity: 'Awareness during the dream', sleepQuality: 'Perceived sleep quality', personalFactors: 'Personal factors', notes: 'Brief notes',
    },
    noRecallAction: 'Record no recall',
    saveOfflineNote: 'Saved on this device first. Optional sync can happen later.',
    neutralOutcome: 'No lucid dream is a normal outcome. Keep sleep and attentive practice as the priorities.',
  },
  weeklyReview: {
    title: 'Weekly review',
    intro: 'Compare methods without turning a small personal sample into a scientific conclusion.',
    metrics: ['Sessions completed', 'Dreams recalled', 'Lucid moments reported', 'Average perceived sleep quality', 'Time needed to return to sleep', 'Techniques skipped for safety'],
    adaptationRules: ['Keep a method only when it fits sleep and daily life.', 'Reduce night practice when sleep quality declines.', 'Change one variable at a time for a clearer comparison.', 'Prefer the least disruptive method when observations are similar.'],
    coachingNote: 'Offline coaching uses these explicit rules. Optional AI may summarize your notes, but core recommendations do not depend on it.',
  },
  science: {
    title: 'Science and limits',
    definition: 'A lucid dream is a dream in which the person becomes aware that they are dreaming while the dream continues. Awareness and control are different; control may be partial or absent.',
    evidenceSummary: 'Research supports lucid dreaming as an REM-sleep phenomenon and identifies MILD, SSILD and WBTB combinations as studied induction approaches. Outcomes vary and many studies rely on self-report.',
    uncertainty: 'No method can predict whether or when an individual will have a lucid dream. Evidence on long-term effects and frequent sleep interruption remains limited.',
    sleepPriority: 'Protect adequate, regular sleep. The AASM and SRS consensus recommends that healthy adults obtain at least seven hours of sleep regularly, while individual needs can differ.',
    boundaries: ['No medical claim or diagnosis', 'No promise of dream control', 'No instruction to reduce needed sleep', 'No substitute for professional support'],
    supportAdvice: 'Pause the training and speak with an appropriate health professional if you have persistent sleep problems, severe distress, confusion between dreams and waking life, or concerns about your mental wellbeing.',
    referencesTitle: 'Sources and reading',
  },
  privacy: {
    title: 'Privacy and your data',
    localFirst: 'Training plans, check-ins and preferences are saved locally first so the core experience works offline.',
    optionalSync: 'Account sync is optional, resilient and clearly shows pending, failed and conflicting changes.',
    minimalTransfer: 'Connecting Noctalia transfers only the item you approve, such as technique and a short morning outcome. Dream text stays separate unless you explicitly choose otherwise in Noctalia.',
    analytics: 'Minimal product analytics are off until consent and never include dream text, free-form notes or audio.',
    sensitiveData: 'Sensitive local values use the platform storage boundary appropriate to their purpose; account credentials are never stored in content files.',
    exportDelete: 'You can export a readable copy or delete local and synced training data from data management.',
    consentControl: 'Consent can be reviewed or withdrawn without blocking offline training.',
  },
  settings: {
    title: 'Settings', reminders: 'Reality-check reminders', sleepWindow: 'Usual sleep window', nightSignals: 'Night audio cues', permissions: 'Permissions', accessibility: 'Accessibility and motion', language: 'Language', appearance: 'Light, dark or system appearance', privacy: 'Privacy and analytics', dataManagement: 'Export and delete data', subscription: 'Noctalia Plus and purchases', noctaliaConnection: 'Connection to Noctalia', scienceAndLimits: 'Science and limits', help: 'Help and safety', about: 'About Lucid Trainer',
  },
} as const satisfies LucidTrainerContent;

export default content;
