import type { LucidTrainerContent } from './types';

const content = {
  locale: 'fr',
  chrome: {
    appName: 'Noctalia Lucid Trainer',
    tagline: 'Entraînez votre attention tout en protégeant votre sommeil.',
    tabs: {
      today: 'Aujourd’hui',
      journal: 'Journal',
      programs: 'Parcours',
      night: 'Nuit',
      progress: 'Insights',
      settings: 'Profil',
    },
    common: {
      continue: 'Continuer',
      back: 'Retour',
      save: 'Enregistrer',
      cancel: 'Annuler',
      done: 'Terminé',
      retry: 'Réessayer',
      skipTonight: 'Passer cette nuit',
      optional: 'Facultatif',
      offlineReady: 'Disponible hors ligne',
      loading: 'Chargement de votre entraînement…',
      error: 'Impossible de charger cet écran. Votre entraînement enregistré reste sur cet appareil.',
    },
  },
  onboarding: {
    title: 'Construisez une pratique du rêve lucide compatible avec votre sommeil',
    intro: 'Lucid Trainer développe l’attention en journée, la préparation au coucher et le bilan du matin. Un rêve lucide peut survenir ou non : la pratique est l’objectif.',
    wellbeingNotice: 'Cet outil concerne le bien-être et l’auto-observation, pas les soins. Protégez d’abord votre sommeil et arrêtez tout exercice qui provoque détresse ou fatigue inhabituelle.',
    goalTitle: 'Que souhaitez-vous entraîner ?',
    goals: [
      { id: 'first_lucid_dream', title: 'Mieux remarquer', description: 'Développer une attention volontaire et repérer les détails inhabituels en allant vers une première expérience lucide.' },
      { id: 'improve_recall', title: 'Se souvenir des rêves', description: 'Consolider l’habitude du matin avant d’ajouter des techniques nocturnes.' },
      { id: 'more_frequent_lucidity', title: 'Explorer plus souvent la lucidité', description: 'Pratiquer des méthodes éclairées par la recherche sans attendre un résultat fixe.' },
      { id: 'stabilize_lucidity', title: 'Rester lucide plus calmement', description: 'Entraîner une réponse calme après avoir reconnu un rêve, sans promettre une expérience plus longue.' },
    ],
    experienceTitle: 'Quelle est votre expérience ?',
    experienceLevels: [
      { id: 'beginner', title: 'Débutant', description: 'Je n’ai jamais suivi de pratique structurée du rêve lucide.' },
      { id: 'occasional', title: 'Occasionnel', description: 'J’ai essayé quelques exercices ou vécu des rêves lucides isolés.' },
      { id: 'experienced', title: 'Régulier', description: 'Je note déjà mes rêves et je veux une routine plus constante.' },
    ],
    reminderTitle: 'Choisissez un rythme réaliste',
    reminderExplanation: 'Commencez par quelques rappels pertinents. Davantage d’alertes ne rend pas un test de réalité plus attentif.',
    sleepScheduleTitle: 'Indiquez votre plage de sommeil habituelle',
    sleepScheduleExplanation: 'Vos horaires de coucher et de réveil maintiennent la préparation et les signaux nocturnes facultatifs dans la plage choisie. Vous pouvez les modifier ou les suspendre à tout moment.',
    permissionsTitle: 'Des autorisations seulement au bon moment',
    notificationPermission: 'Les notifications ne sont demandées qu’après la création d’un rappel. Si vous refusez, l’entraînement reste utilisable avec des invitations manuelles.',
    audioPermission: 'L’audio nocturne est désactivé au départ. Écoutez-le éveillé, réglez un volume discret et un minuteur, puis décidez de l’activer ou non. Le microphone n’est pas nécessaire.',
    accessibilityTitle: 'Adaptez l’expérience',
    accessibilityBody: 'La taille de texte système, les lecteurs d’écran, la réduction des animations et les apparences dynamique, claire ou sombre sont prises en charge. Les étapes essentielles ne reposent jamais uniquement sur la couleur ou le mouvement.',
    consentTitle: 'Vos choix restent les vôtres',
    consentItems: [
      'L’entraînement fonctionne hors ligne sans compte.',
      'Les statistiques produit sont minimales et facultatives.',
      'Connecter Noctalia et transférer un court bilan matinal sont deux choix distincts et révocables.',
      'Vous pouvez exporter ou supprimer vos données d’entraînement depuis les réglages.',
    ],
    finishAction: 'Créer mon plan d’entraînement',
  },
  programs: {
    mild: {
      id: 'mild',
      title: 'MILD',
      expandedName: 'Induction mnémotechnique des rêves lucides',
      summary: 'Répétez une intention claire de reconnaître un futur rêve à partir d’une scène mémorisée et d’un signe de rêve personnel.',
      evidenceNote: 'MILD fait partie des méthodes cognitives les mieux étudiées, mais la qualité des études et les résultats individuels varient.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023', 'stumbrys-2012'],
      prerequisites: [
        'Conservez une possibilité de sommeil stable.',
        'Préparez un rêve récent ou une scène imaginée pour la répétition mentale.',
        'Acceptez de noter un bref résultat le matin, y compris une absence de souvenir.',
      ],
      stopRules: [
        'Suspendez la pratique nocturne après une mauvaise nuit ou une fatigue diurne marquée.',
        'Revenez à une pratique au coucher si un réveil rend le rendormissement difficile.',
        'Arrêtez et cherchez un soutien adapté si les exercices provoquent une détresse ou brouillent les expériences de veille et de rêve.',
      ],
      sessions: [
        {
          id: 'mild-01', session: 1, title: 'Formuler une intention précise',
          objective: 'Comprendre MILD et choisir une intention courte et crédible.', durationMinutes: 10,
          steps: ['Lisez une fois le résumé de la méthode.', 'Écrivez : « Quand je rêverai, j’ai l’intention de le remarquer. »', 'Répétez lentement cette intention trois fois, en cherchant à vous en souvenir plutôt qu’à forcer un résultat.'],
          caution: 'Entraînez-vous éveillé aujourd’hui ; ne raccourcissez pas votre sommeil pour terminer cette séance.',
          reflectionPrompt: 'Quels mots rendent votre intention claire et calme ?',
        },
        {
          id: 'mild-02', session: 2, title: 'Trouver un signe de rêve',
          objective: 'Repérer un détail récurrent ou inhabituel pouvant déclencher la prise de conscience.', durationMinutes: 12,
          steps: ['Relisez un rêve récent ou utilisez une scène imaginée neutre.', 'Choisissez un lieu, un événement, une personne ou une sensation étrange.', 'Imaginez que vous remarquez ce signe et que vous vous arrêtez pour vous demander si vous rêvez.'],
          caution: 'Choisissez une scène neutre si le rappel d’un rêve est désagréable.',
          reflectionPrompt: 'Quel signe serait le plus facile à reconnaître sans effort ?',
        },
        {
          id: 'mild-03', session: 3, title: 'Entraîner la mémoire prospective',
          objective: 'Vous exercer à retrouver une intention lorsqu’un indice futur apparaît.', durationMinutes: 8,
          steps: ['Choisissez trois indices ordinaires pour aujourd’hui, comme ouvrir une porte.', 'À chaque indice, faites une pause et retrouvez votre intention lucide avant de consulter l’application.', 'Marquez l’indice comme remarqué ; les oublis sont des observations utiles, pas des échecs.'],
          caution: 'Utilisez ces indices seulement dans des moments sûrs, jamais en conduisant ou en manipulant du matériel.',
          reflectionPrompt: 'Quel contexte vous a aidé à vous souvenir sans notification ?',
        },
        {
          id: 'mild-04', session: 4, title: 'Répéter le moment de reconnaissance',
          objective: 'Associer l’intention, le signe de rêve et une réaction calme.', durationMinutes: 12,
          steps: ['Reprenez votre scène choisie depuis le début.', 'Au signe de rêve, imaginez que vous remarquez : « C’est un rêve. »', 'Imaginez que vous observez calmement les alentours, puis répétez une fois votre intention.'],
          caution: 'Gardez une répétition brève et arrêtez si les images deviennent stimulantes près du coucher.',
          reflectionPrompt: 'Quelle action calme vous aiderait à rester orienté dans la scène imaginée ?',
        },
        {
          id: 'mild-05', session: 5, title: 'Utiliser MILD au coucher',
          objective: 'Réaliser une séquence MILD peu perturbante avant le sommeil habituel.', durationMinutes: 10,
          steps: ['Préparez votre bilan matinal avant de vous mettre au lit.', 'Rappelez la scène, remarquez le signe et répétez votre intention.', 'Relâchez l’exercice et laissez le sommeil venir normalement.'],
          caution: 'Si la répétition vous maintient éveillé, arrêtez et reprenez votre routine habituelle de détente.',
          reflectionPrompt: 'La séquence était-elle apaisante, neutre ou stimulante ?',
        },
        {
          id: 'mild-06', session: 6, title: 'Pratique facultative après un réveil naturel',
          objective: 'Essayer MILD après un réveil spontané sans programmer de perte de sommeil.', durationMinutes: 6,
          steps: ['Utilisez seulement un réveil naturel avec assez de temps de sommeil restant.', 'Rappelez le fragment de rêve tout juste vécu ou reprenez votre scène habituelle.', 'Posez l’intention une ou deux fois, puis privilégiez le rendormissement.'],
          caution: 'Passez cette séance après un sommeil insuffisant ou si les réveils vous empêchent souvent de vous rendormir.',
          reflectionPrompt: 'Combien de temps vous a-t-il fallu pour vous calmer après l’exercice ?',
        },
        {
          id: 'mild-07', session: 7, title: 'Faire le bilan et adapter',
          objective: 'Choisir un rythme MILD durable à partir de vos observations.', durationMinutes: 15,
          steps: ['Comparez le rappel, la qualité du sommeil et les notes de lucidité de la semaine.', 'Gardez la version la plus courte qui n’a pas perturbé votre sommeil.', 'Planifiez deux ou trois nuits de pratique en intercalant des nuits de récupération après les essais exigeants.'],
          caution: 'N’augmentez pas la fréquence pour compenser une semaine sans lucidité.',
          reflectionPrompt: 'Quelle partie mérite d’être conservée même sans rêve lucide ?',
        },
      ],
    },
    ssild: {
      id: 'ssild',
      title: 'SSILD',
      expandedName: 'Rêve lucide initié par les sens',
      summary: 'Déplacez une attention détendue entre la vue, l’ouïe et les sensations corporelles, sans chercher à produire une expérience.',
      evidenceNote: 'SSILD présente des résultats encourageants dans des études de terrain, mais moins de réplications indépendantes que MILD.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023'],
      prerequisites: [
        'Soyez à l’aise avec l’observation des sensations sans les juger.',
        'Sachez arrêter et revenir au repos normal si l’attention devient laborieuse.',
        'Rendez toutes les consignes essentielles accessibles hors ligne avant le coucher.',
      ],
      stopRules: [
        'Arrêtez les cycles s’ils augmentent l’éveil ou l’inconfort.',
        'Évitez la pratique après réveil lorsque le temps de sommeil est limité.',
        'Choisissez plutôt un exercice d’ancrage en journée si les sensations internes sont déstabilisantes.',
      ],
      sessions: [
        {
          id: 'ssild-01', session: 1, title: 'Observer sans produire',
          objective: 'Apprendre l’attention passive, un sens à la fois.', durationMinutes: 9,
          steps: ['Asseyez-vous confortablement en journée.', 'Remarquez pendant une minute l’obscurité visuelle ou la lumière ambiante.', 'Observez les sons, puis les contacts et la température, en laissant chaque expérience rester ordinaire.'],
          caution: 'Gardez les yeux ouverts si les fermer est inconfortable ou désorientant.',
          reflectionPrompt: 'Quel sens était le plus facile à observer sans effort ?',
        },
        {
          id: 'ssild-02', session: 2, title: 'Apprendre les cycles rapides',
          objective: 'Passer légèrement de la vue aux sons puis au corps.', durationMinutes: 8,
          steps: ['Accordez quelques secondes détendues à la vue.', 'Passez aux sons pendant quelques secondes.', 'Passez aux sensations corporelles, puis répétez quatre cycles sans compter précisément.'],
          caution: 'Ne retenez pas votre souffle, ne forcez pas vos yeux et ne recherchez pas de sensation inhabituelle.',
          reflectionPrompt: 'Avez-vous pu déplacer votre attention sans vérifier si quelque chose de spécial arrivait ?',
        },
        {
          id: 'ssild-03', session: 3, title: 'Apprendre les cycles lents',
          objective: 'Maintenir une attention douce à travers les trois sens.', durationMinutes: 12,
          steps: ['Posez votre attention sur la vue pendant environ vingt secondes.', 'Passez à l’ouïe, puis aux sensations corporelles pendant des durées semblables et souples.', 'Effectuez quatre cycles lents et terminez avant que la concentration ne devienne un travail.'],
          caution: 'Estimez le temps ; regarder l’heure peut rendre l’exercice plus stimulant.',
          reflectionPrompt: 'À quel moment l’observation détendue est-elle devenue un effort ?',
        },
        {
          id: 'ssild-04', session: 4, title: 'Construire la séquence complète',
          objective: 'Combiner les cycles rapides et lents en une routine familière.', durationMinutes: 14,
          steps: ['Effectuez quatre cycles rapides.', 'Effectuez quatre cycles lents.', 'Terminez par une respiration normale et élargissez votre attention à tout le corps.'],
          caution: 'Il s’agit d’une répétition éveillée ; ne modifiez pas vos horaires de sommeil habituels.',
          reflectionPrompt: 'Quel indice simple vous rappellera de rester passif ?',
        },
        {
          id: 'ssild-05', session: 5, title: 'Essayer une version au coucher',
          objective: 'Utiliser une séquence raccourcie sans retarder le sommeil.', durationMinutes: 8,
          steps: ['Installez-vous dans votre position de sommeil habituelle.', 'Effectuez deux cycles rapides puis deux cycles lents.', 'Arrêtez volontairement et laissez venir le sommeil, même si la séquence paraît incomplète.'],
          caution: 'Si la séquence retarde le sommeil, retirez-la du coucher et conservez seulement la pratique en journée.',
          reflectionPrompt: 'La version courte a-t-elle respecté votre détente du soir ?',
        },
        {
          id: 'ssild-06', session: 6, title: 'Séquence facultative après un réveil',
          objective: 'Essayer la séquence complète après un réveil naturel lorsque les conditions conviennent.', durationMinutes: 10,
          steps: ['Vérifiez qu’il reste assez de temps pour dormir et que vous vous sentez calme.', 'Effectuez quatre cycles rapides, puis quatre à six cycles lents.', 'Terminez l’exercice et rendormez-vous sans l’évaluer.'],
          caution: 'Passez cette séance après une mauvaise nuit, pendant une maladie ou avant une journée exigeant une vigilance maximale.',
          reflectionPrompt: 'Avez-vous pu vous rendormir confortablement ?',
        },
        {
          id: 'ssild-07', session: 7, title: 'Choisir une dose durable',
          objective: 'Adapter SSILD selon vos notes de sommeil et d’expérience, sans pression de résultat.', durationMinutes: 15,
          steps: ['Relisez l’assiduité, la qualité du sommeil, le rappel et la lucidité.', 'Choisissez une pratique en journée, au coucher ou occasionnellement après un réveil.', 'Planifiez des nuits de récupération et gardez la version la moins perturbante qui vous convient.'],
          caution: 'Une semaine neutre est un résultat valable ; n’ajoutez pas automatiquement des cycles ou des réveils.',
          reflectionPrompt: 'Quelle version était assez calme pour être répétée ?',
        },
      ],
    },
    wbtb: {
      id: 'wbtb',
      title: 'WBTB',
      expandedName: 'Réveil puis retour au lit',
      summary: 'Utilisez un réveil planifié ou naturel en fin de nuit, un court intervalle calme et un retour au sommeil avec une technique cognitive choisie.',
      evidenceNote: 'WBTB est souvent associé à MILD ou SSILD. Comme il interrompt le sommeil, il doit rester occasionnel et subordonné aux besoins de repos.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023', 'aasm-srs-2015'],
      prerequisites: [
        'Réservez assez de temps pour votre durée de sommeil normale et le bref réveil.',
        'Choisissez un matin sans obligation précoce exigeant une vigilance critique.',
        'Décidez de la technique calme à utiliser avant de régler une alarme.',
      ],
      stopRules: [
        'Annulez après une dette de sommeil, une maladie, une fatigue inhabituelle ou des réveils répétés.',
        'Raccourcissez l’intervalle d’éveil si vous devenez trop alerte.',
        'Suspendez WBTB si la qualité du sommeil ou votre fonctionnement en journée se dégrade.',
      ],
      sessions: [
        {
          id: 'wbtb-01', session: 1, title: 'Vérifier si les conditions conviennent',
          objective: 'Savoir quand éviter WBTB avant même de programmer une alarme.', durationMinutes: 10,
          steps: ['Évaluez votre temps de sommeil récent et votre vigilance en journée.', 'Listez les obligations et besoins de sécurité du lendemain matin.', 'Écrivez une règle claire d’annulation pour cette nuit.'],
          caution: 'Cette séance ne comporte aucun réveil nocturne ; n’essayez pas WBTB si vous manquez déjà de sommeil.',
          reflectionPrompt: 'Quel signal indiquera que passer la séance est le choix responsable ?',
        },
        {
          id: 'wbtb-02', session: 2, title: 'Préparer un réveil discret',
          objective: 'Configurer une alarme facultative qui limite les perturbations.', durationMinutes: 10,
          steps: ['Choisissez une nuit occasionnelle avec assez de temps au lit.', 'Sélectionnez une alarme douce et un moyen simple de l’arrêter.', 'Préparez un éclairage tamisé et les consignes hors ligne avant le coucher.'],
          caution: 'Ne dormez pas avec un casque ou des écouteurs et évitez tout volume susceptible de vous faire sursauter ou de réveiller les autres.',
          reflectionPrompt: 'Pouvez-vous annuler la configuration sans perdre votre progression ?',
        },
        {
          id: 'wbtb-03', session: 3, title: 'Répéter l’intervalle d’éveil en journée',
          objective: 'Apprendre une séquence courte et peu stimulante avant de l’utiliser la nuit.', durationMinutes: 12,
          steps: ['Entraînez-vous à vous lever lentement avec une lumière tamisée.', 'Lisez une courte fiche de technique sans ouvrir d’autres applications.', 'Retournez au lit et respirez calmement pendant deux minutes.'],
          caution: 'Cette répétition en journée remplace une tentative nocturne aujourd’hui.',
          reflectionPrompt: 'Quelle étape pourrait créer une stimulation inutile la nuit ?',
        },
        {
          id: 'wbtb-04', session: 4, title: 'Choisir la technique associée',
          objective: 'Associer WBTB à une seule méthode connue plutôt que d’improviser.', durationMinutes: 10,
          steps: ['Choisissez l’intention MILD ou la séquence SSILD déjà pratiquée.', 'Placez seulement cette consigne près du lit.', 'Fixez une durée maximale d’éveil et un point d’arrêt.'],
          caution: 'Ne combinez pas plusieurs méthodes et ne prolongez pas l’éveil pour poursuivre un résultat.',
          reflectionPrompt: 'Quelle technique unique est la plus facile à réaliser calmement ?',
        },
        {
          id: 'wbtb-05', session: 5, title: 'Première nuit facultative',
          objective: 'Effectuer une tentative WBTB prudente en protégeant le sommeil.', durationMinutes: 15,
          steps: ['Au réveil, réévaluez votre fatigue et annulez si les conditions ont changé.', 'Restez dans une lumière tamisée uniquement pendant le court intervalle prévu.', 'Effectuez la technique choisie, retournez au lit et relâchez l’objectif.'],
          caution: 'Arrêtez immédiatement si vous vous sentez mal ou trop éveillé ; privilégiez le retour au repos.',
          reflectionPrompt: 'La séquence complète a-t-elle perturbé votre sommeil, indépendamment du rêve ?',
        },
        {
          id: 'wbtb-06', session: 6, title: 'Protéger la journée suivante',
          objective: 'Utiliser votre fonctionnement en journée comme signal de sécurité pour les prochains essais.', durationMinutes: 8,
          steps: ['Évaluez honnêtement la qualité de votre sommeil et votre vigilance.', 'N’effectuez pas une nouvelle tentative WBTB cette nuit.', 'En cas de somnolence, évitez la conduite et les tâches dangereuses, puis appliquez vos mesures de sécurité habituelles.'],
          caution: 'Les données d’entraînement ne passent jamais avant la sécurité immédiate ou le repos nécessaire.',
          reflectionPrompt: 'La tentative a-t-elle affecté votre concentration, votre humeur ou votre énergie ?',
        },
        {
          id: 'wbtb-07', session: 7, title: 'Définir un rythme occasionnel',
          objective: 'Décider si WBTB a réellement sa place dans votre plan.', durationMinutes: 15,
          steps: ['Comparez le sommeil, le temps de rendormissement, le rappel et la lucidité.', 'Conservez WBTB seulement si les perturbations sont restées faibles.', 'Choisissez une fréquence maximale prudente avec des nuits de récupération, ou désactivez la méthode.'],
          caution: 'Ne programmez pas WBTB comme une obligation quotidienne ; le désactiver constitue un plan complet.',
          reflectionPrompt: 'L’intérêt possible justifie-t-il pour vous cette interruption du sommeil ?',
        },
      ],
    },
  },
  realityChecks: {
    title: 'Tests de réalité attentifs',
    intro: 'Un bon test interrompt brièvement le pilotage automatique : observez le contexte, vérifiez un détail stable et imaginez reconnaître le même décalage dans un rêve.',
    qualityPrinciples: ['Faites une pause avant d’agir.', 'Posez la question avec une incertitude sincère.', 'Utilisez deux indices plutôt qu’une habitude seule.', 'Terminez par une intention calme pour le prochain rêve.'],
    exercises: [
      { id: 'text', title: 'Lire deux fois', description: 'Lisez une courte phrase, détournez le regard, puis relisez-la et vérifiez si elle reste stable.' },
      { id: 'time', title: 'Vérifier l’heure deux fois', description: 'Regardez l’heure, détournez les yeux, puis comparez sans vous presser.' },
      { id: 'hands', title: 'Observer ses mains', description: 'Comptez les doigts et remarquez la forme, la texture et la continuité sans chercher à provoquer une anomalie.' },
      { id: 'context', title: 'Retracer le contexte', description: 'Demandez-vous comment vous êtes arrivé ici et nommez les deux derniers événements dont vous vous souvenez.' },
    ],
    contextTitle: 'Associez les tests à des contextes pertinents',
    contextExamples: ['Après avoir remarqué quelque chose de surprenant', 'En entrant dans une pièce familière', 'Après l’apaisement d’une émotion forte', 'Quand un signe de rêve personnel récurrent apparaît en journée'],
    reminderSafety: 'Ignorez un rappel lorsque votre attention est nécessaire ailleurs. Ne faites jamais de test en conduisant, en traversant une route ou en utilisant du matériel.',
    completionPrompt: 'Quel indice avez-vous réellement vérifié ?',
  },
  nightSignals: {
    title: 'Signaux audio nocturnes facultatifs',
    intro: 'Un signal est une invitation discrète, pas un ordre. Son minuteur ne connaît pas votre phase de sommeil sans détection séparément validée : choisissez donc des réglages prudents et jugez-le selon son impact sur votre sommeil.',
    optionalLabel: 'Désactivé au départ',
    setupSteps: ['Écoutez le son exact en étant bien éveillé.', 'Commencez au volume le plus bas qui reste audible.', 'Choisissez un minuteur court avec arrêt automatique.', 'Vérifiez que demain permet un temps de récupération normal.'],
    safeguards: ['Ne dormez pas avec un casque ou des écouteurs.', 'N’utilisez pas de signal s’il dérange un partenaire, un enfant ou un animal.', 'Évitez les signaux après une mauvaise nuit, une maladie ou une fatigue inhabituelle.', 'Arrêtez un signal s’il vous réveille ou vous fait sursauter à plusieurs reprises.'],
    previewAction: 'Écouter en étant éveillé',
    timerLabel: 'Minuteur d’arrêt automatique',
    volumeLabel: 'Volume doux du signal',
    stopAction: 'Arrêter tous les signaux nocturnes',
  },
  morningReview: {
    title: 'Bilan du matin',
    intro: 'Note ce qui s’est passé avant toute interprétation. Une nuit sans souvenir ou sans lucidité apporte aussi une information utile.',
    fields: {
      technique: 'Technique utilisée', preparation: 'Préparation effectuée', dreamRecall: 'Rappel du rêve', lucidity: 'Conscience pendant le rêve', sleepQuality: 'Qualité perçue du sommeil', personalFactors: 'Facteurs personnels', notes: 'Notes brèves',
    },
    noRecallAction: 'Noter aucun souvenir',
    saveOfflineNote: 'Enregistré d’abord sur cet appareil. La synchronisation facultative peut avoir lieu plus tard.',
    neutralOutcome: 'L’absence de rêve lucide est un résultat habituel. Le sommeil et la qualité de la pratique restent prioritaires.',
  },
  weeklyReview: {
    title: 'Bilan hebdomadaire',
    intro: 'Comparez les méthodes sans transformer un petit échantillon personnel en conclusion scientifique.',
    metrics: ['Séances terminées', 'Rêves rappelés', 'Moments lucides déclarés', 'Qualité moyenne perçue du sommeil', 'Temps nécessaire pour se rendormir', 'Techniques passées par prudence'],
    adaptationRules: ['Gardez une méthode seulement si elle convient à votre sommeil et à votre vie quotidienne.', 'Réduisez la pratique nocturne lorsque la qualité du sommeil baisse.', 'Modifiez une variable à la fois pour mieux comparer.', 'Préférez la méthode la moins perturbante lorsque les observations se ressemblent.'],
    coachingNote: 'Le coaching hors ligne applique ces règles explicites. Une IA facultative peut résumer vos notes, mais les recommandations essentielles n’en dépendent pas.',
  },
  science: {
    title: 'Science et limites',
    definition: 'Un rêve lucide est un rêve dans lequel une personne prend conscience qu’elle rêve tandis que le rêve continue. Conscience et contrôle sont différents ; le contrôle peut être partiel ou absent.',
    evidenceSummary: 'La recherche décrit le rêve lucide comme un phénomène du sommeil paradoxal et étudie MILD, SSILD et leurs associations avec WBTB. Les résultats varient et de nombreuses études reposent sur des déclarations personnelles.',
    uncertainty: 'Aucune méthode ne permet de prévoir si ou quand une personne vivra un rêve lucide. Les connaissances sur les effets à long terme et les interruptions fréquentes du sommeil restent limitées.',
    sleepPriority: 'Protégez un sommeil suffisant et régulier. Le consensus AASM/SRS recommande aux adultes en bonne santé de dormir régulièrement au moins sept heures, tout en reconnaissant des besoins individuels différents.',
    boundaries: ['Aucune affirmation de soin ni évaluation clinique', 'Aucune maîtrise du rêve attendue', 'Aucune consigne de réduire le sommeil nécessaire', 'Ne remplace pas un accompagnement professionnel'],
    supportAdvice: 'Suspendez l’entraînement et parlez à un professionnel de santé adapté en cas de problèmes de sommeil persistants, de détresse intense, de confusion entre rêve et veille ou d’inquiétude concernant votre bien-être mental.',
    referencesTitle: 'Sources et lectures',
  },
  privacy: {
    title: 'Confidentialité et données',
    localFirst: 'Les plans, bilans et préférences sont d’abord enregistrés localement afin que l’expérience essentielle fonctionne hors ligne.',
    optionalSync: 'La synchronisation du compte est facultative et résiliente ; elle indique clairement les modifications en attente, en échec ou en conflit.',
    minimalTransfer: 'Connecter Noctalia transfère seulement l’élément que vous approuvez, comme la technique et un court résultat matinal. Le texte des rêves reste séparé sauf choix explicite dans Noctalia.',
    analytics: 'Les statistiques produit minimales restent désactivées sans consentement et n’incluent jamais le texte des rêves, les notes libres ou l’audio.',
    sensitiveData: 'Les valeurs locales sensibles utilisent la protection de la plateforme adaptée à leur usage ; les identifiants du compte ne sont jamais stockés dans les fichiers de contenu.',
    exportDelete: 'Vous pouvez exporter une copie lisible ou supprimer les données d’entraînement locales et synchronisées depuis la gestion des données.',
    consentControl: 'Le consentement peut être revu ou retiré sans bloquer l’entraînement hors ligne.',
  },
  settings: {
    title: 'Réglages', reminders: 'Rappels des tests de réalité', sleepWindow: 'Plage de sommeil habituelle', nightSignals: 'Signaux audio nocturnes', permissions: 'Autorisations', accessibility: 'Accessibilité et animations', language: 'Langue', appearance: 'Apparence dynamique, claire, sombre ou système', privacy: 'Confidentialité et statistiques', dataManagement: 'Exporter et supprimer les données', subscription: 'Noctalia Plus et achats', noctaliaConnection: 'Connexion à Noctalia', scienceAndLimits: 'Science et limites', help: 'Aide et sécurité', about: 'À propos de Lucid Trainer',
  },
} as const satisfies LucidTrainerContent;

export default content;
