import type { LucidTrainerContent } from './types';

const content = {
  locale: 'fr',
  chrome: {
    appName: 'Noctalia Lucid Trainer',
    tagline: 'Entraîne ton attention tout en protégeant ton sommeil.',
    tabs: {
      today: 'Aujourd’hui',
      journal: 'Journal',
      programs: 'Parcours',
      night: 'Nuit',
      progress: 'Insights',
      settings: 'Profil',
    },
    common: {
      continue: 'Continuer',
      back: 'Retour',
      save: 'Enregistrer',
      cancel: 'Annuler',
      done: 'Terminé',
      retry: 'Réessayer',
      skipTonight: 'Passer cette nuit',
      optional: 'Facultatif',
      offlineReady: 'Disponible hors ligne',
      loading: 'Chargement de ton entraînement…',
      error: 'Impossible de charger cet écran. Ton entraînement enregistré reste sur cet appareil.',
    },
  },
  onboarding: {
    title: 'Construis une pratique du rêve lucide compatible avec ton sommeil',
    intro: 'Lucid Trainer développe l’attention en journée, la préparation au coucher et le bilan du matin. Un rêve lucide peut survenir ou non : la pratique est l’objectif.',
    wellbeingNotice: 'Cet outil concerne le bien-être et l’auto-observation, pas les soins. Protège d’abord ton sommeil et arrête tout exercice qui provoque détresse ou fatigue inhabituelle.',
    goalTitle: 'Que souhaites-tu entraîner ?',
    goals: [
      { id: 'first_lucid_dream', title: 'Mieux remarquer', description: 'Développer une attention volontaire et repérer les détails inhabituels en allant vers une première expérience lucide.' },
      { id: 'improve_recall', title: 'Se souvenir des rêves', description: 'Consolider l’habitude du matin avant d’ajouter des techniques nocturnes.' },
      { id: 'more_frequent_lucidity', title: 'Explorer plus souvent la lucidité', description: 'Pratiquer des méthodes éclairées par la recherche sans attendre un résultat fixe.' },
      { id: 'stabilize_lucidity', title: 'Rester lucide plus calmement', description: 'Entraîner une réponse calme après avoir reconnu un rêve, sans promettre une expérience plus longue.' },
    ],
    experienceTitle: 'Quelle est ton expérience ?',
    experienceLevels: [
      { id: 'beginner', title: 'Débutant', description: 'Je n’ai jamais suivi de pratique structurée du rêve lucide.' },
      { id: 'occasional', title: 'Occasionnel', description: 'J’ai essayé quelques exercices ou vécu des rêves lucides isolés.' },
      { id: 'experienced', title: 'Régulier', description: 'Je note déjà mes rêves et je veux une routine plus constante.' },
    ],
    reminderTitle: 'Choisis un rythme réaliste',
    reminderExplanation: 'Commence par quelques rappels pertinents. Davantage d’alertes ne rend pas un test de réalité plus attentif.',
    sleepScheduleTitle: 'Indique ta plage de sommeil habituelle',
    sleepScheduleExplanation: 'Tes horaires de coucher et de réveil maintiennent la préparation et les signaux nocturnes facultatifs dans la plage choisie. Tu peux les modifier ou les suspendre à tout moment.',
    permissionsTitle: 'Des autorisations seulement au bon moment',
    notificationPermission: 'Les notifications ne sont demandées qu’après la création d’un rappel. Si tu refuses, l’entraînement reste utilisable avec des invitations manuelles.',
    audioPermission: 'L’audio nocturne est désactivé au départ. Écoute-le éveillé, règle un volume discret et un minuteur, puis décide de l’activer ou non. Le microphone n’est pas nécessaire.',
    accessibilityTitle: 'Adapte l’expérience',
    accessibilityBody: 'La taille de texte système, les lecteurs d’écran, la réduction des animations et les apparences dynamique, claire ou sombre sont prises en charge. Les étapes essentielles ne reposent jamais uniquement sur la couleur ou le mouvement.',
    consentTitle: 'Tes choix restent les tiens',
    consentItems: [
      'L’entraînement fonctionne hors ligne sans compte.',
      'Les statistiques produit sont minimales et facultatives.',
      'Connecter Noctalia et transférer un court bilan matinal sont deux choix distincts et révocables.',
      'Tu peux exporter ou supprimer tes données d’entraînement depuis les réglages.',
    ],
    finishAction: 'Créer mon plan d’entraînement',
  },
  programs: {
    mild: {
      id: 'mild',
      title: 'MILD',
      expandedName: 'Induction mnémotechnique des rêves lucides',
      summary: 'Répète une intention claire de reconnaître un futur rêve à partir d’une scène mémorisée et d’un signe de rêve personnel.',
      evidenceNote: 'MILD fait partie des méthodes cognitives les mieux étudiées, mais la qualité des études et les résultats individuels varient.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023', 'stumbrys-2012'],
      prerequisites: [
        'Conserve une possibilité de sommeil stable.',
        'Prépare un rêve récent ou une scène imaginée pour la répétition mentale.',
        'Accepte de noter un bref résultat le matin, y compris une absence de souvenir.',
      ],
      stopRules: [
        'Suspends la pratique nocturne après une mauvaise nuit ou une fatigue diurne marquée.',
        'Reviens à une pratique au coucher si un réveil rend le rendormissement difficile.',
        'Arrête et cherche un soutien adapté si les exercices provoquent une détresse ou brouillent les expériences de veille et de rêve.',
      ],
      sessions: [
        {
          id: 'mild-01', session: 1, title: 'Formuler une intention précise',
          objective: 'Comprendre MILD et choisir une intention courte et crédible.', durationMinutes: 10,
          steps: ['Lis une fois le résumé de la méthode.', 'Écris : « Quand je rêverai, j’ai l’intention de le remarquer. »', 'Répète lentement cette intention trois fois, en cherchant à t’en souvenir plutôt qu’à forcer un résultat.'],
          caution: 'Entraîne-toi éveillé aujourd’hui ; ne raccourcis pas ton sommeil pour terminer cette séance.',
          reflectionPrompt: 'Quels mots rendent ton intention claire et calme ?',
        },
        {
          id: 'mild-02', session: 2, title: 'Trouver un signe de rêve',
          objective: 'Repérer un détail récurrent ou inhabituel pouvant déclencher la prise de conscience.', durationMinutes: 12,
          steps: ['Relis un rêve récent ou utilise une scène imaginée neutre.', 'Choisis un lieu, un événement, une personne ou une sensation étrange.', 'Imagine que tu remarques ce signe et que tu t’arrêtes pour te demander si tu rêves.'],
          caution: 'Choisis une scène neutre si le rappel d’un rêve est désagréable.',
          reflectionPrompt: 'Quel signe serait le plus facile à reconnaître sans effort ?',
        },
        {
          id: 'mild-03', session: 3, title: 'Entraîner la mémoire prospective',
          objective: 'T’exercer à retrouver une intention lorsqu’un indice futur apparaît.', durationMinutes: 8,
          steps: ['Choisis trois indices ordinaires pour aujourd’hui, comme ouvrir une porte.', 'À chaque indice, fais une pause et retrouve ton intention lucide avant de consulter l’application.', 'Marque l’indice comme remarqué ; les oublis sont des observations utiles, pas des échecs.'],
          caution: 'Utilise ces indices seulement dans des moments sûrs, jamais en conduisant ou en manipulant du matériel.',
          reflectionPrompt: 'Quel contexte t’a aidé à te souvenir sans notification ?',
        },
        {
          id: 'mild-04', session: 4, title: 'Répéter le moment de reconnaissance',
          objective: 'Associer l’intention, le signe de rêve et une réaction calme.', durationMinutes: 12,
          steps: ['Reprends ta scène choisie depuis le début.', 'Au signe de rêve, imagine que tu remarques : « C’est un rêve. »', 'Imagine que tu observes calmement les alentours, puis répète une fois ton intention.'],
          caution: 'Garde une répétition brève et arrête si les images deviennent stimulantes près du coucher.',
          reflectionPrompt: 'Quelle action calme t’aiderait à rester orienté dans la scène imaginée ?',
        },
        {
          id: 'mild-05', session: 5, title: 'Utiliser MILD au coucher',
          objective: 'Réaliser une séquence MILD peu perturbante avant le sommeil habituel.', durationMinutes: 10,
          steps: ['Prépare ton bilan matinal avant de te mettre au lit.', 'Rappelle la scène, remarque le signe et répète ton intention.', 'Relâche l’exercice et laisse le sommeil venir normalement.'],
          caution: 'Si la répétition te maintient éveillé, arrête et reprends ta routine habituelle de détente.',
          reflectionPrompt: 'La séquence était-elle apaisante, neutre ou stimulante ?',
        },
        {
          id: 'mild-06', session: 6, title: 'Pratique facultative après un réveil naturel',
          objective: 'Essayer MILD après un réveil spontané sans programmer de perte de sommeil.', durationMinutes: 6,
          steps: ['Utilise seulement un réveil naturel avec assez de temps de sommeil restant.', 'Rappelle le fragment de rêve tout juste vécu ou reprends ta scène habituelle.', 'Pose l’intention une ou deux fois, puis privilégie le rendormissement.'],
          caution: 'Passe cette séance après un sommeil insuffisant ou si les réveils t’empêchent souvent de te rendormir.',
          reflectionPrompt: 'Combien de temps t’a-t-il fallu pour te calmer après l’exercice ?',
        },
        {
          id: 'mild-07', session: 7, title: 'Faire le bilan et adapter',
          objective: 'Choisir un rythme MILD durable à partir de tes observations.', durationMinutes: 15,
          steps: ['Compare le rappel, la qualité du sommeil et les notes de lucidité de la semaine.', 'Garde la version la plus courte qui n’a pas perturbé ton sommeil.', 'Planifie deux ou trois nuits de pratique en intercalant des nuits de récupération après les essais exigeants.'],
          caution: 'N’augmente pas la fréquence pour compenser une semaine sans lucidité.',
          reflectionPrompt: 'Quelle partie mérite d’être conservée même sans rêve lucide ?',
        },
      ],
    },
    ssild: {
      id: 'ssild',
      title: 'SSILD',
      expandedName: 'Rêve lucide initié par les sens',
      summary: 'Déplace une attention détendue entre la vue, l’ouïe et les sensations corporelles, sans chercher à produire une expérience.',
      evidenceNote: 'SSILD présente des résultats encourageants dans des études de terrain, mais moins de réplications indépendantes que MILD.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023'],
      prerequisites: [
        'Sois à l’aise avec l’observation des sensations sans les juger.',
        'Sache arrêter et revenir au repos normal si l’attention devient laborieuse.',
        'Rends toutes les consignes essentielles accessibles hors ligne avant le coucher.',
      ],
      stopRules: [
        'Arrête les cycles s’ils augmentent l’éveil ou l’inconfort.',
        'Évite la pratique après réveil lorsque le temps de sommeil est limité.',
        'Choisis plutôt un exercice d’ancrage en journée si les sensations internes sont déstabilisantes.',
      ],
      sessions: [
        {
          id: 'ssild-01', session: 1, title: 'Observer sans produire',
          objective: 'Apprendre l’attention passive, un sens à la fois.', durationMinutes: 9,
          steps: ['Assieds-toi confortablement en journée.', 'Remarque pendant une minute l’obscurité visuelle ou la lumière ambiante.', 'Observe les sons, puis les contacts et la température, en laissant chaque expérience rester ordinaire.'],
          caution: 'Garde les yeux ouverts si les fermer est inconfortable ou désorientant.',
          reflectionPrompt: 'Quel sens était le plus facile à observer sans effort ?',
        },
        {
          id: 'ssild-02', session: 2, title: 'Apprendre les cycles rapides',
          objective: 'Passer légèrement de la vue aux sons puis au corps.', durationMinutes: 8,
          steps: ['Accorde quelques secondes détendues à la vue.', 'Passe aux sons pendant quelques secondes.', 'Passe aux sensations corporelles, puis répète quatre cycles sans compter précisément.'],
          caution: 'Ne retiens pas ton souffle, ne force pas tes yeux et ne recherche pas de sensation inhabituelle.',
          reflectionPrompt: 'As-tu pu déplacer ton attention sans vérifier si quelque chose de spécial arrivait ?',
        },
        {
          id: 'ssild-03', session: 3, title: 'Apprendre les cycles lents',
          objective: 'Maintenir une attention douce à travers les trois sens.', durationMinutes: 12,
          steps: ['Pose ton attention sur la vue pendant environ vingt secondes.', 'Passe à l’ouïe, puis aux sensations corporelles pendant des durées semblables et souples.', 'Effectue quatre cycles lents et termine avant que la concentration ne devienne un travail.'],
          caution: 'Estime le temps ; regarder l’heure peut rendre l’exercice plus stimulant.',
          reflectionPrompt: 'À quel moment l’observation détendue est-elle devenue un effort ?',
        },
        {
          id: 'ssild-04', session: 4, title: 'Construire la séquence complète',
          objective: 'Combiner les cycles rapides et lents en une routine familière.', durationMinutes: 14,
          steps: ['Effectue quatre cycles rapides.', 'Effectue quatre cycles lents.', 'Termine par une respiration normale et élargis ton attention à tout le corps.'],
          caution: 'Il s’agit d’une répétition éveillée ; ne modifie pas tes horaires de sommeil habituels.',
          reflectionPrompt: 'Quel indice simple te rappellera de rester passif ?',
        },
        {
          id: 'ssild-05', session: 5, title: 'Essayer une version au coucher',
          objective: 'Utiliser une séquence raccourcie sans retarder le sommeil.', durationMinutes: 8,
          steps: ['Installe-toi dans ta position de sommeil habituelle.', 'Effectue deux cycles rapides puis deux cycles lents.', 'Arrête volontairement et laisse venir le sommeil, même si la séquence paraît incomplète.'],
          caution: 'Si la séquence retarde le sommeil, retire-la du coucher et conserve seulement la pratique en journée.',
          reflectionPrompt: 'La version courte a-t-elle respecté ta détente du soir ?',
        },
        {
          id: 'ssild-06', session: 6, title: 'Séquence facultative après un réveil',
          objective: 'Essayer la séquence complète après un réveil naturel lorsque les conditions conviennent.', durationMinutes: 10,
          steps: ['Vérifie qu’il reste assez de temps pour dormir et que tu te sens calme.', 'Effectue quatre cycles rapides, puis quatre à six cycles lents.', 'Termine l’exercice et rendors-toi sans l’évaluer.'],
          caution: 'Passe cette séance après une mauvaise nuit, pendant une maladie ou avant une journée exigeant une vigilance maximale.',
          reflectionPrompt: 'As-tu pu te rendormir confortablement ?',
        },
        {
          id: 'ssild-07', session: 7, title: 'Choisir une dose durable',
          objective: 'Adapter SSILD selon tes notes de sommeil et d’expérience, sans pression de résultat.', durationMinutes: 15,
          steps: ['Relis l’assiduité, la qualité du sommeil, le rappel et la lucidité.', 'Choisis une pratique en journée, au coucher ou occasionnellement après un réveil.', 'Planifie des nuits de récupération et garde la version la moins perturbante qui te convient.'],
          caution: 'Une semaine neutre est un résultat valable ; n’ajoute pas automatiquement des cycles ou des réveils.',
          reflectionPrompt: 'Quelle version était assez calme pour être répétée ?',
        },
      ],
    },
    wbtb: {
      id: 'wbtb',
      title: 'WBTB',
      expandedName: 'Réveil puis retour au lit',
      summary: 'Utilise un réveil planifié ou naturel en fin de nuit, un court intervalle calme et un retour au sommeil avec une technique cognitive choisie.',
      evidenceNote: 'WBTB est souvent associé à MILD ou SSILD. Comme il interrompt le sommeil, il doit rester occasionnel et subordonné aux besoins de repos.',
      evidenceReferenceIds: ['ildis-2020', 'tan-fan-2023', 'aasm-srs-2015'],
      prerequisites: [
        'Réserve assez de temps pour ta durée de sommeil normale et le bref réveil.',
        'Choisis un matin sans obligation précoce exigeant une vigilance critique.',
        'Décide de la technique calme à utiliser avant de régler une alarme.',
      ],
      stopRules: [
        'Annule après une dette de sommeil, une maladie, une fatigue inhabituelle ou des réveils répétés.',
        'Raccourcis l’intervalle d’éveil si tu deviens trop alerte.',
        'Suspends WBTB si la qualité du sommeil ou ton fonctionnement en journée se dégrade.',
      ],
      sessions: [
        {
          id: 'wbtb-01', session: 1, title: 'Vérifier si les conditions conviennent',
          objective: 'Savoir quand éviter WBTB avant même de programmer une alarme.', durationMinutes: 10,
          steps: ['Évalue ton temps de sommeil récent et ta vigilance en journée.', 'Liste les obligations et besoins de sécurité du lendemain matin.', 'Écris une règle claire d’annulation pour cette nuit.'],
          caution: 'Cette séance ne comporte aucun réveil nocturne ; n’essaie pas WBTB si tu manques déjà de sommeil.',
          reflectionPrompt: 'Quel signal indiquera que passer la séance est le choix responsable ?',
        },
        {
          id: 'wbtb-02', session: 2, title: 'Préparer un réveil discret',
          objective: 'Configurer une alarme facultative qui limite les perturbations.', durationMinutes: 10,
          steps: ['Choisis une nuit occasionnelle avec assez de temps au lit.', 'Sélectionne une alarme douce et un moyen simple de l’arrêter.', 'Prépare un éclairage tamisé et les consignes hors ligne avant le coucher.'],
          caution: 'Ne dors pas avec un casque ou des écouteurs et évite tout volume susceptible de te faire sursauter ou de réveiller les autres.',
          reflectionPrompt: 'Peux-tu annuler la configuration sans perdre ta progression ?',
        },
        {
          id: 'wbtb-03', session: 3, title: 'Répéter l’intervalle d’éveil en journée',
          objective: 'Apprendre une séquence courte et peu stimulante avant de l’utiliser la nuit.', durationMinutes: 12,
          steps: ['Entraîne-toi à te lever lentement avec une lumière tamisée.', 'Lis une courte fiche de technique sans ouvrir d’autres applications.', 'Retourne au lit et respire calmement pendant deux minutes.'],
          caution: 'Cette répétition en journée remplace une tentative nocturne aujourd’hui.',
          reflectionPrompt: 'Quelle étape pourrait créer une stimulation inutile la nuit ?',
        },
        {
          id: 'wbtb-04', session: 4, title: 'Choisir la technique associée',
          objective: 'Associer WBTB à une seule méthode connue plutôt que d’improviser.', durationMinutes: 10,
          steps: ['Choisis l’intention MILD ou la séquence SSILD déjà pratiquée.', 'Place seulement cette consigne près du lit.', 'Fixe une durée maximale d’éveil et un point d’arrêt.'],
          caution: 'Ne combine pas plusieurs méthodes et ne prolonge pas l’éveil pour poursuivre un résultat.',
          reflectionPrompt: 'Quelle technique unique est la plus facile à réaliser calmement ?',
        },
        {
          id: 'wbtb-05', session: 5, title: 'Première nuit facultative',
          objective: 'Effectuer une tentative WBTB prudente en protégeant le sommeil.', durationMinutes: 15,
          steps: ['Au réveil, réévalue ta fatigue et annule si les conditions ont changé.', 'Reste dans une lumière tamisée uniquement pendant le court intervalle prévu.', 'Effectue la technique choisie, retourne au lit et relâche l’objectif.'],
          caution: 'Arrête immédiatement si tu te sens mal ou trop éveillé ; privilégie le retour au repos.',
          reflectionPrompt: 'La séquence complète a-t-elle perturbé ton sommeil, indépendamment du rêve ?',
        },
        {
          id: 'wbtb-06', session: 6, title: 'Protéger la journée suivante',
          objective: 'Utiliser ton fonctionnement en journée comme signal de sécurité pour les prochains essais.', durationMinutes: 8,
          steps: ['Évalue honnêtement la qualité de ton sommeil et ta vigilance.', 'N’effectue pas une nouvelle tentative WBTB cette nuit.', 'En cas de somnolence, évite la conduite et les tâches dangereuses, puis applique tes mesures de sécurité habituelles.'],
          caution: 'Les données d’entraînement ne passent jamais avant la sécurité immédiate ou le repos nécessaire.',
          reflectionPrompt: 'La tentative a-t-elle affecté ta concentration, ton humeur ou ton énergie ?',
        },
        {
          id: 'wbtb-07', session: 7, title: 'Définir un rythme occasionnel',
          objective: 'Décider si WBTB a réellement sa place dans ton plan.', durationMinutes: 15,
          steps: ['Compare le sommeil, le temps de rendormissement, le rappel et la lucidité.', 'Conserve WBTB seulement si les perturbations sont restées faibles.', 'Choisis une fréquence maximale prudente avec des nuits de récupération, ou désactive la méthode.'],
          caution: 'Ne programme pas WBTB comme une obligation quotidienne ; le désactiver constitue un plan complet.',
          reflectionPrompt: 'L’intérêt possible justifie-t-il pour toi cette interruption du sommeil ?',
        },
      ],
    },
  },
  realityChecks: {
    title: 'Tests de réalité attentifs',
    intro: 'Un bon test interrompt brièvement le pilotage automatique : observe le contexte, vérifie un détail stable et imagine reconnaître le même décalage dans un rêve.',
    qualityPrinciples: ['Fais une pause avant d’agir.', 'Pose la question avec une incertitude sincère.', 'Utilise deux indices plutôt qu’une habitude seule.', 'Termine par une intention calme pour le prochain rêve.'],
    exercises: [
      { id: 'text', title: 'Lire deux fois', description: 'Lis une courte phrase, détourne le regard, puis relis-la et vérifie si elle reste stable.' },
      { id: 'time', title: 'Vérifier l’heure deux fois', description: 'Regarde l’heure, détourne les yeux, puis compare sans te presser.' },
      { id: 'hands', title: 'Observer ses mains', description: 'Compte les doigts et remarque la forme, la texture et la continuité sans chercher à provoquer une anomalie.' },
      { id: 'context', title: 'Retracer le contexte', description: 'Demande-toi comment tu es arrivé ici et nomme les deux derniers événements dont tu te souviens.' },
    ],
    contextTitle: 'Associe les tests à des contextes pertinents',
    contextExamples: ['Après avoir remarqué quelque chose de surprenant', 'En entrant dans une pièce familière', 'Après l’apaisement d’une émotion forte', 'Quand un signe de rêve personnel récurrent apparaît en journée'],
    reminderSafety: 'Ignore un rappel lorsque ton attention est nécessaire ailleurs. Ne fais jamais de test en conduisant, en traversant une route ou en utilisant du matériel.',
    completionPrompt: 'Quel indice as-tu réellement vérifié ?',
  },
  nightSignals: {
    title: 'Signaux audio nocturnes facultatifs',
    intro: 'Un signal est une invitation discrète, pas un ordre. Son minuteur ne connaît pas ta phase de sommeil sans détection séparément validée : choisis donc des réglages prudents et juge-le selon son impact sur ton sommeil.',
    optionalLabel: 'Désactivé au départ',
    setupSteps: ['Écoute le son exact en étant bien éveillé.', 'Commence au volume le plus bas qui reste audible.', 'Choisis un minuteur court avec arrêt automatique.', 'Vérifie que demain permet un temps de récupération normal.'],
    safeguards: ['Ne dors pas avec un casque ou des écouteurs.', 'N’utilise pas de signal s’il dérange un partenaire, un enfant ou un animal.', 'Évite les signaux après une mauvaise nuit, une maladie ou une fatigue inhabituelle.', 'Arrête un signal s’il te réveille ou te fait sursauter à plusieurs reprises.'],
    previewAction: 'Écouter en étant éveillé',
    timerLabel: 'Minuteur d’arrêt automatique',
    volumeLabel: 'Volume doux du signal',
    stopAction: 'Arrêter tous les signaux nocturnes',
  },
  morningReview: {
    title: 'Bilan du matin',
    intro: 'Note ce qui s’est passé avant toute interprétation. Une nuit sans souvenir ou sans lucidité apporte aussi une information utile.',
    fields: {
      technique: 'Technique utilisée', preparation: 'Préparation effectuée', dreamRecall: 'Rappel du rêve', lucidity: 'Conscience pendant le rêve', sleepQuality: 'Qualité perçue du sommeil', personalFactors: 'Facteurs personnels', notes: 'Notes brèves',
    },
    noRecallAction: 'Noter aucun souvenir',
    saveOfflineNote: 'Enregistré d’abord sur cet appareil. La synchronisation facultative peut avoir lieu plus tard.',
    neutralOutcome: 'L’absence de rêve lucide est un résultat habituel. Le sommeil et la qualité de la pratique restent prioritaires.',
  },
  weeklyReview: {
    title: 'Bilan hebdomadaire',
    intro: 'Compare les méthodes sans transformer un petit échantillon personnel en conclusion scientifique.',
    metrics: ['Séances terminées', 'Rêves rappelés', 'Moments lucides déclarés', 'Qualité moyenne perçue du sommeil', 'Temps nécessaire pour se rendormir', 'Techniques passées par prudence'],
    adaptationRules: ['Garde une méthode seulement si elle convient à ton sommeil et à ta vie quotidienne.', 'Réduis la pratique nocturne lorsque la qualité du sommeil baisse.', 'Modifie une variable à la fois pour mieux comparer.', 'Préfère la méthode la moins perturbante lorsque les observations se ressemblent.'],
    coachingNote: 'Le coaching hors ligne applique ces règles explicites. Une IA facultative peut résumer tes notes, mais les recommandations essentielles n’en dépendent pas.',
  },
  science: {
    title: 'Science et limites',
    definition: 'Un rêve lucide est un rêve dans lequel une personne prend conscience qu’elle rêve tandis que le rêve continue. Conscience et contrôle sont différents ; le contrôle peut être partiel ou absent.',
    evidenceSummary: 'La recherche décrit le rêve lucide comme un phénomène du sommeil paradoxal et étudie MILD, SSILD et leurs associations avec WBTB. Les résultats varient et de nombreuses études reposent sur des déclarations personnelles.',
    uncertainty: 'Aucune méthode ne permet de prévoir si ou quand une personne vivra un rêve lucide. Les connaissances sur les effets à long terme et les interruptions fréquentes du sommeil restent limitées.',
    sleepPriority: 'Protège un sommeil suffisant et régulier. Le consensus AASM/SRS recommande aux adultes en bonne santé de dormir régulièrement au moins sept heures, tout en reconnaissant des besoins individuels différents.',
    boundaries: ['Aucune affirmation de soin ni évaluation clinique', 'Aucune maîtrise du rêve attendue', 'Aucune consigne de réduire le sommeil nécessaire', 'Ne remplace pas un accompagnement professionnel'],
    supportAdvice: 'Suspends l’entraînement et parle à un professionnel de santé adapté en cas de problèmes de sommeil persistants, de détresse intense, de confusion entre rêve et veille ou d’inquiétude concernant ton bien-être mental.',
    referencesTitle: 'Sources et lectures',
  },
  privacy: {
    title: 'Confidentialité et données',
    localFirst: 'Les plans, bilans et préférences sont d’abord enregistrés localement afin que l’expérience essentielle fonctionne hors ligne.',
    optionalSync: 'La synchronisation du compte est facultative et résiliente ; elle indique clairement les modifications en attente, en échec ou en conflit.',
    minimalTransfer: 'Connecter Noctalia transfère seulement l’élément que tu approuves, comme la technique et un court résultat matinal. Le texte des rêves reste séparé sauf choix explicite dans Noctalia.',
    analytics: 'Les statistiques produit minimales restent désactivées sans consentement et n’incluent jamais le texte des rêves, les notes libres ou l’audio.',
    sensitiveData: 'Les valeurs locales sensibles utilisent la protection de la plateforme adaptée à leur usage ; les identifiants du compte ne sont jamais stockés dans les fichiers de contenu.',
    exportDelete: 'Tu peux exporter une copie lisible ou supprimer les données d’entraînement locales et synchronisées depuis la gestion des données.',
    consentControl: 'Le consentement peut être revu ou retiré sans bloquer l’entraînement hors ligne.',
  },
  settings: {
    title: 'Réglages', reminders: 'Rappels des tests de réalité', sleepWindow: 'Plage de sommeil habituelle', nightSignals: 'Signaux audio nocturnes', permissions: 'Autorisations', accessibility: 'Accessibilité et animations', language: 'Langue', appearance: 'Apparence dynamique, claire, sombre ou système', privacy: 'Confidentialité et statistiques', dataManagement: 'Exporter et supprimer les données', subscription: 'Noctalia Plus et achats', noctaliaConnection: 'Connexion à Noctalia', scienceAndLimits: 'Science et limites', help: 'Aide et sécurité', about: 'À propos de Lucid Trainer',
  },
} as const satisfies LucidTrainerContent;

export default content;
